#1 만들고 싶은 습관 CRUD TODO
wanted-pre-onboarding-side-project/habit-tracker pull request #14
Opened 2023-04-04 06:30 UTC by jiyeon2

### 작업 내용
해빗 생성, 수정, 삭제, 목록 조회 함수 및 컴포넌트 작성
생성된 해빗 정보는 로컬스토리지에 저장
![image 1](https://user-images.githubusercontent.com/18395475/229686960-a2f03c3b-f146-44c8-8fe2-2d94396efabe.jpg)
![image 2](https://user-images.githubusercontent.com/18395475/229686974-c85cc981-f2ba-42f4-ba03-af5de23a1fc6.jpg)

### 디렉토리 구조
```
src
├── index.tsx     // ContextProvider 초기화
├── App.tsx       // 라우터 적용 예정
├──service
│   └── HabitManager.ts        // 해빗 생성, 삭제, 수정, 목록조회하는 핵심기능
├── context
│   └── HabitContext.tsx     //  해빗 생성, 삭제, 수정, 목록 조회하는 함수를 컴포넌트에 전달
└── components
     ├── HabitTracker.tsx
     ├── HabitRow.tsx
     └── HabitDetailForm.tsx

```

### 주안점
- 해빗트래커의 주요 기능을 각각 하나의 함수로 만들기로 함. 어떤 인자를 받아 어떤 값을 리턴할 것인지 고려하여 HabitManager 인터페이스 작성
- 핵심 기능과 인터페이스 모아둔 HabitManager.ts 파일은 외부 모듈, 파일에 의존하지 않도록 작성함
![Group 4](https://user-images.githubusercontent.com/18395475/229687238-304d4ae6-beb1-49a6-a7ac-773fda38b2bd.jpg)

- HabitProvider의 props에서는 LocalHabitManager클래스가 아닌  HabitManager 인터페이스를 참조하여 구체가 아닌 추상에 의존하도록 함 (의존성 역전), index.tsx에서 LocalHabitManager인스턴스를 주입받음(의존성 주입)

### 메모
- HabitContext에서 날짜정보(year, month, lastDay)를  관리할 필요가 없어 보임
- HabitAdd, HabitRow 컴포넌트 내부 이벤트핸들러를 hook으로 분리하여 필요한 형태로 받아오면 컴포넌트 내부 코드가 더 간략해질듯 함

close #1

2023-04-04 09:21 UTC, greyHairChooseLife requested changes
고생하셨습니다! 궁금한 것이 많아서 몇 번 주고 받고 해야할것같아요!

2023-04-04 09:21 UTC, greyHairChooseLife commented on src/App.tsx
> +      <HabitTracker />
이렇게 한번 depth를 준 것은 향후 라우팅을 고려한 것인가요?

2023-04-04 09:21 UTC, greyHairChooseLife commented on src/components/HabitDetailForm.tsx
> +      <form onSubmit={onSubmit} id={HABIT_DETAIL_FORM_ID}>
chakra의 form컴포넌트를 사용하지 않은 이유가 혹시 있을까요?

2023-04-04 09:21 UTC, greyHairChooseLife commented on src/components/HabitDetailForm.tsx
> +    // 좋은 방법이 떠오르지 않음..
저도 해 보진 않았는데요, <input> 컴포넌트에 type속성을 전부 명시 해 주면 되지 않을까 싶어요.

2023-04-04 09:21 UTC, greyHairChooseLife commented on src/components/HabitDetailForm.tsx
> +export interface HabitFormProps {
이 인터페이스의 속성이 옵셔널하게 사용되는 시나리오는 어떤 것들이 있나요?

2023-04-04 09:21 UTC, greyHairChooseLife commented on src/components/HabitDetailForm.tsx
> +  title: string;
HabitDrawer 컴포넌트가 여러곳에서 사용 되는 듯 한데, title props 속성이 무엇을 뜻하는지 좀 더 표현 해 주었다면 좋았을 것 같습니다.

props 이름 자체를 구체적으로 짓거나 아니면 Habit 인터페이스에서 추출하거나.. 아니면 주석이라도 있으면 어떨까 싶습니다. 그러면 그런 '추상'을 보고 <HabitDrawer > 컴포넌트를 사용하기 수월할 것 같아서요.

2023-04-04 09:21 UTC, greyHairChooseLife commented on src/context/HabitContext.tsx
> +export const useHabitContext = () => {
1. 커스텀 훅과 컴포넌트를 그래도 분리하면 어떨까 싶습니다.
2. 지금 useHabitContext라는 커스텀훅의 존재 의의는 Provider 내에서 사용하지 않은 경우에 에러를 뱉어주는 것 뿐입니다.
위에서 createContext함수로 컨텍스트를 생성 할 때 default값을 null로 주셨는데 차라리 디폴트 값을 주고 useContext hook을 wrapping 하지 않고 사용하는 것은 어떨까요?

2023-04-04 09:21 UTC, greyHairChooseLife commented on src/context/HabitContext.tsx
> +
context provider를 분리할 필요가 있어 보입니다. 이벤트 핸들러와 값이 섞여 있다보니 이벤트만 한번 실행 시켜도 컨텍스트를 구독하는 모든 컴포넌트가 리렌더링 될 것입니다.

또 이벤트 핸들러를 넘겨줄 때 useCallback으로 memoization하는게 좋아보입니다. 이벤트 핸들러와 여타 상태값들을 분리 했을 때, memoized된 요소들만 구독하고 있는 컴포넌트들의 무의미한 리렌더링을 막을 수 있습니다.

2023-04-04 09:21 UTC, greyHairChooseLife commented on src/service/HabitManager.ts
커스텀 훅 대신 클래스를 통해 전역 상태를 관리하는 이유는 무엇인가요?

2023-04-04 15:37 UTC, jiyeon2 commented on src/App.tsx
> +      <HabitTracker />
네 맞습니다~ 
index.tsx에서는 provider를 설정하고
App.tsx에서는 라우터를 적용하려고 했어요!

2023-04-04 15:43 UTC, jiyeon2 commented on src/components/HabitDetailForm.tsx
> +      <form onSubmit={onSubmit} id={HABIT_DETAIL_FORM_ID}>
chakra-ui에서 제공하는 `<form>` 컴포넌트는 없는걸로 알고 있습니다~ 
공식문서에서 [Formik이라는 라이브러리를 사용한 예제](https://chakra-ui.com/docs/components/form-control/usage#usage-with-form-libraries)는 봤는데 적용은 해보지 않았습니다
폼 관련 라이브러리를 사용하면 유효성 검사 등도 더 쉽게 할 수 있을거 같아요
상연님은 혹시 Formik이라는 라이브러리를 사용해 보신 적이 있으신가요?

2023-04-04 15:55 UTC, jiyeon2 commented on src/components/HabitDetailForm.tsx
> +    // 좋은 방법이 떠오르지 않음..
의견 주셔서 감사합니다~
`<Input type="text">` 과 같이 타입을 명시해도
FormData.get 의 리턴타입이 FormDataEntryValue | null 이라
string으로 자동으로 추론해주지는 않네요..
다른 방법을 생각해보겠습니다!!

2023-04-04 16:11 UTC, jiyeon2 commented on src/components/HabitDetailForm.tsx
> +export interface HabitFormProps {
HabitDetailForm 컴포넌트를 두 가지 용도로 사용하고 있습니다
1. 습관생성
2. 습관수정

습관 수정의 경우
옵셔널로 설정된 habitName, habitDescription 값을 전달받아 
input의 기본값으로 표시합니다!

HabitFormProps 옵셔널 속성 이름을 아래와 같이 바꾸면 
더 이해하기가 쉬울까요..??
```ts
export interface HabitFormProps {
  defaultHabitName?: string;
  defaultHabitDescription?: string;
  ...
}
```

2023-04-04 16:53 UTC, jiyeon2 commented on src/components/HabitDetailForm.tsx
> +  title: string;
Drawer 컴포넌트의 제목이니 title이면 되겠지 싶어서 만든건데
뜻을 명확하게 전달하지 못했네요!!
혼자 개발하면 이런 부분을 알아채기가 어려운데
자세히 보고 언급해주셔서 감사합니다~~ :tada: 

상연님이 제시해 주신 의견을 토대로
컴포넌트의 의도를 더 잘 나타내고자
아래와 같이 코드를 수정했습니다 [470ee2b](https://github.com/wanted-pre-onboarding-side-project/habit-tracker/pull/14/commits/470ee2bb8d2d7f9825ac0310a22479dab171f2ca)

1. HabitDrawer는 HabitDetailForm(습관생성,수정 폼)을 화면에 표시하거나 숨기는 역할이므로 title 을 props로 받을 필요가 없다 => title을 HabitDetailForm의 props로 옮겨 폼의 제목을 나타내는 props임을 명시함

2. Drawer 형태가 아닌 Modal 등 다른 형태의 오버레이 ui로 바뀔 수 있다는 생각이 들어
HabitDetailFormContainer와 같은 일반적인 이름으로 변경

2023-04-04 17:32 UTC, jiyeon2 commented on src/context/HabitContext.tsx
> +export const useHabitContext = () => {
1. 코드가 짧고 HabitContext와 관련성이 깊다고 생각해서 분리해야하나 고민했었어요! 앞으로 다른 커스텀 훅을 만들면 /hooks 등의 폴더에 모아둘  거 같아서 동일한 기준으로 관리하기 위해 분리하겠습니다~

2. 저는 에러를 뱉는게 중요한 역할이라고 생각합니다~ 
개발자가 실수로 HabitProvider 외부에서 컨텍스트에 접근한다면 의미없는 초기값만 계속 리턴될텐데
오류를 뱉지 않으면 본인의 실수를 인지하기 어렵습니다
(오늘 `<ChakraProvider>` 적용 안하고 쓰는데 오류가 안나와서 ui 적용 안되는 이유를 몰라 잠깐 헤맸습니다 :face_exhaling: )

커스텀 훅으로 래핑하지 않는 방법은 
컨텍스트를 사용하고 싶은 모든 곳에서 
useContext, HabitContext 두 가지를 import 해야 하는 게 번거로워 좋아하지 않습니다..

상연님은 context api 사용하실 때 커스텀 훅으로 래핑해서 사용하는 것보다 
디폴트 값을 설정해서 사용하시는 걸 더 선호하시나요?? 
혹시 그러시다면 어떤 점이 좋은지 의견 남겨 주시면 감사하겠습니다!

2023-04-04 18:44 UTC, jiyeon2 commented on src/context/HabitContext.tsx
> +
좋은 의견 감사합니다~~
컨텍스트가 하나뿐인데 그걸 구독하고 있는 컴포넌트가 많아서
뭔가 하나 누를 때마다 렌더링이 일어나더라고요..

Habit과 관련이 없는 month, year등은 PeriodContext로 분리하였고,
HabitContext도 HabitValueContext, HabitActionContext 컨텍스트로 나눴습니다

HabitActionContext provider에서 전달하는 함수는
이벤트핸들러로 사용되므로 useCallback 함수로 감쌌습니다

불필요한 리렌더링이 일어나지 않도록
다른 컨텍스트를 구독하는 컴포넌트를 만들었습니다(HabitRows)

2023-04-04 19:41 UTC, jiyeon2 commented on src/service/HabitManager.ts
전역 상태 habits는 HabitProvider에서 관리합니다!

HabitProvider는 HabitManager를 통해 받은 habits를 저장합니다
LocalHabitManager 클래스에서도 habits, checks 값을 가지고 있어서
클래스에서 전역상태를 관리하는 걸로 보였나봅니다..

LocalHabitManager에서 habits 값을 중복해서 가지고 있다는 생각이 들어
클래스 내부 변수를 삭제하고 로컬스토리지에서 바로 가져오는 형태로 수정하였습니다

클래스를 사용한 이유는 2주차 세션 복습하며 해당 코드를 많이 참고했기 때문입니다
HabitManager 인터페이스를 만족한다면 클래스가 아닌 일반 객체를 사용해도 상관없을듯 합니다~

2023-04-05 08:28 UTC, greyHairChooseLife commented on src/components/HabitDetailForm.tsx
> +      <form onSubmit={onSubmit} id={HABIT_DETAIL_FORM_ID}>
앗, 저는 form 자체를 잘 안쓰다보니 공식 문서를 제대로 보지 않았네요. '<formControll>' 어쩌구 하는 애들이 자기들 나름대로 이름 지어 놓은 form인줄 알았네요. :baby_chick:

2023-04-05 09:21 UTC, jiyeon2 commented on src/components/HabitDetailForm.tsx
> +      <form onSubmit={onSubmit} id={HABIT_DETAIL_FORM_ID}>
저도 FormControl이 폼인가 싶었는데 `<form>`을 래핑한 컴포넌트는 없는거 
같아서 그냥 `<form>`을 사용했습니다!

2023-04-06 06:44 UTC, greyHairChooseLife commented on src/components/HabitDetailForm.tsx
> +export interface HabitFormProps {
아, 새로운 habit을 만들 때는 인자로 받아 올 필요가 없으니까 옵셔널이군요.

저는 `기존 habits` 상태값과 `새로운/업데이트하는 habit`의 `form`을  분리 할 생각을 못했다보니 미처 못알아봤습니다.

어찌보면 옵셔널하게 주었다는 것 자체가 (제가 모자라서 못알아들었을 뿐이지 ㅋㅋ) 충분한 정보 전달이긴 한데, 그래도 이렇게 이름까지 더 구체적으로 적어주시니까 더 알아보기 쉬울 것 같긴 합니다. 제가 죄송해지네요.. ㅋㅋ

별거 아닌 딴지를 걸자면 default.. 보단 current가 좀 더 분명하게 의미 전달 해 줄 것 같습니다. 자세한 설명 감사해요.

2023-04-06 06:51 UTC, greyHairChooseLife commented on src/components/HabitDetailForm.tsx
> +  title: string;
컴포넌트의 겉모습(?)을 표현하는 이름인 Drawer에서 용도를 표현하는 땡땡Form 이렇게 바꾸니까 훨씬 잘 알아들을 수 있겠습니다. :+1: 

---

저는 habit 수정이나 새로 생성 할 때 인라인에서 태그만 바뀌는 방식으로 하다 보니 title이 필요하다는 생각 자체를 못했습니다. 가만 보니 제가 보는 눈이 없는 거였던 듯 한데, 어쨌든 지연님이 더 읽기 쉽게 해 주시다보니 훨씬 알아듣기 쉬워지긴 합니다.  :+1:

2023-04-06 06:52 UTC, jiyeon2 commented on src/components/HabitDetailForm.tsx
> +export interface HabitFormProps {
오 current라는 단어는 떠올리질 못했어요
좋은 의견 감사합니다!! :+1:

2023-04-06 07:01 UTC, greyHairChooseLife commented on src/context/HabitContext.tsx
> +export const useHabitContext = () => {
저부터도 임포트 피하기 위해서, 또 커스텀 훅이라는 사실을 표현하기 위해서도 래핑해서 쓰는데 말을 저렇게 했네요.

제 말의 요지는 Provider로 감싸지지 않은 채로 context를 사용한다면, createContext에서 default로 넣은 값을 리턴하기 때문에, default에 '이 값을 본다니, 너 제대로 providing 하지 않고 있구나' 라는 의미를 넣어 두는 것은 어떤가 하는 거였어요.

 아예 에러를 throw하는게 개발 도중에 더 분명하게 의미 전달을 할 것 같긴 하네요.

2023-04-06 07:41 UTC, jiyeon2 commented on src/context/HabitContext.tsx
> +
{ createHabit, deleteHabit, updateHabitDetail, updateHabitCheck } 자체를 메모해야함
{ habits,checks }

2023-04-06 10:42 UTC, closed without merging