Feature #30
wanted-pre-onboarding-side-project/habit-tracker pull request #40
Opened 2023-04-13 01:43 UTC by chadseok

### 1. 무슨 이유로 코드를 추가/변경 했는지
   - #30 의 요구사항대로 헤더, 컨트롤러, 대쉬보드 기능을 구현하기 위해 기능에 해당하는 컴포넌트들을 생성하였습니다
   - 이번에는 pure css로 구현했기 때문에 따로 css파일을 만들고 css파일을 적용할 컴포넌트 파일을 같은 곳에 두고 싶어서 컴포넌트 이름으로 된 폴더를 생성하였습니다
   - `Controller` 컴포넌트에서 week을 바꾸는 로직이 React State값을 쓰기 때문에 이것을 따로 hooks(`useSelectWeekRange`)로 분리하였습니다
   - 회의에서 결정한대로 날짜 연산을 쉽게 하기 위해 `dayjs`를 설치하였습니다
   - `helpers` 폴더에는 컴포넌트나 hooks에서 필요한 복잡한 날짜 연산 로직을 처리해주는 함수들을 모아놨습니다
   - 메인 기능인 habit tracker기능을 만들기 전에 임시 데이터로 작업을 하기 위해 `mock/data.json`을 추가하였습니다

### 2. 파일 구조와 용도
- `src`폴더 밖에는 추가된 파일이 없습니다
- `src`폴더 구조
```
📦src
 ┣ 📂components
 ┃ ┣ 📂Contoller
 ┃ ┃ ┣ ➕Controller.module.css
 ┃ ┃ ┗ ➕index.tsx
 ┃ ┣ 📂DashBoard
 ┃ ┃ ┣ ➕DashBoard.module.css
 ┃ ┃ ┣ ➕DashBoardItem.tsx
 ┃ ┃ ┗ ➕index.tsx
 ┃ ┣ 📂Header
 ┃ ┃ ┣ ➕Header.module.css
 ┃ ┃ ┗ ➕index.tsx
 ┃ ┗ 📂ProgressBar
 ┃ ┃ ┣ ➕ProgressBar.module.css
 ┃ ┃ ┗ ➕index.tsx
 ┣ 📂helpers
 ┃ ┣ ➕calculateDateByWeek.ts
 ┃ ┣ ➕getFormattedDate.ts
 ┃ ┗ ➕getWeekRangeByDate.ts
 ┣ 📂hooks
 ┃ ┗ ➕useSelectWeekRange.tsx
 ┣ 📂mock
 ┃ ┗ ➕data.json
 ┣ ➕App.module.css
 ┣ App.tsx
 ┣ index.css
 ┣ index.tsx
 ┣ react-app-env.d.ts
 ┣ reportWebVitals.ts
 ┗ setupTests.ts
```

- 전체 화면에서 차지하는 컴포넌트 영역

<img src='https://user-images.githubusercontent.com/83488329/231623994-5d189aca-55ec-4519-b5c2-30c29cc952bb.png' width='400' alt='structure'/>

### 3. 어떤 부분에 리뷰어가 집중하면 좋을지

지금 메인 기능은 개발하지 않아서 전역상태 관리를 하는 부분같은 복잡한 로직을 작성하지는 않았습니다.
그래서 리뷰어 분 께서는 `App.tsx` -> `Components` 폴더 순으로 차례대로 보시면서 전체 구조를 파악하고 
Controller에서 hooks가 동작하는 것과 관련된 helpers의 보조함수의 로직 위주로 세부적인 코드에 집중해주시면 좋을 것 같습니다

### 4. 관련 스크린샷 or GIF

- 전체 이미지
<img width="840" alt="스크린샷 2023-04-13 오전 10 17 16" src="https://user-images.githubusercontent.com/83488329/231620905-d9a5f27f-ce18-4287-a1bb-ad17e78a489b.png">

- 주 변경(제일 최근에 왔을 때는 다음주로 가기 비활성화)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/83488329/231621726-7b03e97e-abda-4a95-96eb-e703fdde5f23.gif)

2023-04-13 05:31 UTC, jiyeon2 approved these changes, later dismissed
components/컴포넌트이름 별로 폴더를 구성한 형태가 좋았습니다~
다른곳에서 컴포넌트 사용할 때 
`import Header from "./components/Header";` 
이런식으로 작성한 걸 보니 깔끔해보이더라고요
그리고  css 파일도 같은 폴더에 위치해있어 찾기 쉬웠습니다

css module 방식을 몰랐는데 덕분에 알게되었습니다! :+1: 

helpers 함수들도 순수함수 형태에 작은 단위로 나눠져 있어서
사용하기 편하다는 생각이 들었습니다

구조를 간결하게 잘 만드셔서 파악하기 좋았습니다~ 
추가 설명이 없어도 이해하는데 무리가 없어 
코멘트를 많이 달지 못했습니다..!

2023-04-13 05:31 UTC, jiyeon2 commented on src/components/DashBoard/DashBoardItem.tsx
> +type DashBoardItemProps = {
```ts
type DashBoardItemProps = {
    id: number;
    title: string;
    description: string;
    habitDays: string[];
    checkDays: string[];
  }

<DashBoardItem {...props} />
```
와 같이 써도 될거같은데
```ts
type DashBoardItemProps = { data : {...} }
```
처럼 data: {} 로 한번 더 감싸신 이유가 궁금합니다~ 
추후 data외에 다른 값을 props로 전달할 계획이셨나요?
아니면 `<DashBoardItem data={item} />` 형태로 전달하려고 하신걸까요?

2023-04-13 05:31 UTC, jiyeon2 commented on src/helpers/getWeekRangeByDate.ts
> +});
dayjs 커스터마이징 코드가 
특정 helper 함수 파일내에 존재하면
이 코드를 처음 접한 사람이 찾기 어려울거같아요

src/index.tsx에서 처리하거나 별도의 파일로 분리하는 것은 어떨까요?

2023-04-13 05:31 UTC, jiyeon2 commented on src/hooks/useSelectWeekRange.tsx
복잡하고 세세한 날짜 조작 로직은 helpers 함수로 분리하고
useSelectWeekRange 훅에서 컴포넌트에 필요한 형태로 래핑하여 리턴하는 구조가 깔끔해요~ :+1:  :+1:

2023-04-13 07:49 UTC, chadseok commented on src/components/DashBoard/DashBoardItem.tsx
> +type DashBoardItemProps = {
네 @jiyeon2 님. 일단 기능 개발을 하면서 다른 값이 들어올 수 도 있을 것 같아서 props로 data하나뿐이지만 묶어서 나타내었습니다.

2023-04-13 07:50 UTC, chadseok commented on src/helpers/getWeekRangeByDate.ts
> +});
네 좋은 생각이신 것 같습니다! config파일에 한 번 작성해보도록 할께요!

2023-04-14 02:18 UTC, jiyeon2 commented on src/setupDayjs.ts
이 파일을 index.tsx에서 import만 해도 적용이 되는군요 :+1: 

6번째 줄의 advancedFormat을 사용해야
`dayjs(date).startOf("week").format("dddd, MMM D[일]")` 이 포맷 형식이 가능한 건가요?

[AdvancedFormat](https://day.js.org/docs/en/plugin/advanced-format) 에서 제공하는 포맷 형식 목록에 없어서 
기본으로 제공하는 포맷 형식이 아닌가 싶어서요

2023-04-14 07:26 UTC, chadseok commented on src/setupDayjs.ts
네 @jiyeon2 님. AdvancedFormat을 사용하지 않아도 적용이 됩니다. 

"[일]"이 부분은
제가 `dayjs.locale('kr')`로 적용을 하니까 month 같은 경우에는 한국어로 4월, 5월 이런식으로 뜨던데 뒤에 오는 정확한 날짜는 12일 **이렇게 오는 것이 아니라** 단순히 12, 13 이렇게 뜨더라구요. 그래서 뒤에 일을 표시하기 위해 escape용도로 "[]"를 감쌌습니다

2023-04-15 02:35 UTC, greyHairChooseLife requested changes
## PR 메시지를 보고서

- 목데이터는 보통 `root/public/`에다 두더라고요. 아마도 소스코드에 속하지 않아서 그런 것 같습니다. 꼭 그래야 할까 싶기도 한데, 어쨌든 프로젝트의 구조가 조금이라도 간결해 질 수 있을 것 같습니다.
- 파일 구조 보여주실 때 인덴트 조금 넣어주시면 더 보기 쉬울 것 같습니다.
- css파일은 중간에 `.module`을 넣어주셨는데 이것이 어떤 이익을 주는지 알려주시면 감사하겠습니다!
- components 디렉토리의 내부에 위계가 적절하지 않은 것 같습니다. `controller` 또는 `dashboard` 같은 것은 `ProgressBar`보다는 더 상위 컴포넌트 같아서요. 
- 위 내용은 파일구조 칸 바로 아래 참고 이미지를 보면 더 확실해 지는 것 같습니다. 보면 크게 2개의 컴포넌트로 분리하고 그 구성 컴포넌트들로 표현하셨는데, 여기서 표현 된 위계와 같이 파일 구조를 잡으시면 개발 할 때도, 또 다른 사람이 볼 때도 머릿속에 프로젝트 구조가 딱 그려질 것 같습니다!

## 커밋 히스토리를 보고서

- rename, remove prefix를 사용하셨는데 저는 refactor라고 달았던 것 같아요. 더 좋은 구분이라고 생각합니다. 다만 일단은 규칙에 없으니 제안하고, 팀  컨벤션으로 정해진 뒤에 써 주셨다면 더 좋았을 것 같습니다!
- 다만 지워주실 때 다른 테스트용 파일 등도 같이 지워주시면 좋지 않았을까 싶습니다!
- 247764ed58188ca53e62d819e8028e4e7baf3a25, https://github.com/wanted-pre-onboarding-side-project/habit-tracker/pull/40/commits/247764ed58188ca53e62d819e8028e4e7baf3a25 커밋 메시지로 레퍼런스 달아주실 때 비판적인 의견이나 개선 방향을 새로 이슈를 남기거나 해당 이슈에 댓글로 추가 해 주셨다면 더 좋았을 것 같습니다! 보고서 가봤는데 뭐가 없더라구요!
- 전반적으로 보면 feat prefix를 달고 있지만 개발 스타일 상 style작업이 같이 포함되는데요, 제목에도 반복해서 등장하구요. 이러면은 style prefix를 달아서 스타일링에 관한 내용을 한눈에 살피자는 의미가 퇴색되는 것 같습니다. `git stash`를 이용하거나 해서.. 뭔가 구분 될 수 있으면 좋겠네요!
- chore prefix 달고 패키지 설치 할 때는 설치 이유, 유용함(?)에 대해 아주 간단히 적어주면 좋을 것 같습니다. 저도 이부분 생각 못했는데 패키지 설치 구분하여 커밋하신 것을 보니까 떠올랐습니다!
- 아래와 같은 커밋은 커밋 제목과 내용이 조금 상이 해 보입니다. 코드를 보기 전에는 어떻게 해당 제목과 내용이 연관되는지 이해하기 어려울 것 같습니다.
>feat: 이번주의 항목을 볼때는 다음주를 클릭하는 버튼 비활성화하는 기능 추가 
이번주의 첫번째 날짜와 선택된 날짜에 해당하는 주의 첫번째 날짜랑 비교하는 로직을 작성하였습니다. 첫번째 날짜를 포맷팅된 형태로 구하는 함수를 구현하였습니다
getToday도 비슷한 기능을 하는 것 같아 같은 파일에 두었고 파일이름을 getFormattedDate로 변경하였습니다

2023-04-15 02:35 UTC, greyHairChooseLife commented on src/components/Contoller/index.tsx
> +  const { selectedWeekRange, changeWeekRange, isDisabledToClickNextWeek } =
변수 이름은 지극히 개인적인 영역이라고 생각하긴 하는데요, 그래도 제안 드려보자면
- selectedWeekRange :point_right: weekRange, period
- isDisabledToClickNextWeek :point_right: isLatest

정확히 이런게 좋다라기보다 selected 같은 것은 쓰지 않더라도 리뷰어도 개발자도 모두 쉽게 예상 할 수 있을 것 같습니다! 훅의 이름에도 있고요!

2023-04-15 02:35 UTC, greyHairChooseLife commented on src/components/Contoller/index.tsx
> +    <div className={styles.weekController}>
클래스네임이 전부 styles 객체로부터 오는데, 이것은 어떤 유용함을 주나요?

2023-04-15 02:35 UTC, greyHairChooseLife commented on src/components/DashBoard/DashBoardItem.tsx
> +    checkDays: string[];
- habitDays에는 정해진 요일만 들어올테니 타입을 따로 만들어 쓰면 좋을 것 같습니다!
- checkDays는 요일을 체크 했다기 보단 날짜를 체크 하는 것이 의도하신 바 같은데 checkDates로 하면 명확할 것 같아요!

2023-04-15 02:35 UTC, greyHairChooseLife commented on src/components/DashBoard/DashBoardItem.tsx
> +const today = getToday();
이렇게 컴포넌트 밖에(스크립트에) 상수값으로 지정 된다면 예를들어 밤 11시 55분에 이 어플을 사용하다가 자정이 넘게 되어도 `today`가 바뀌지 않을 것 같습니다.

2023-04-15 02:35 UTC, greyHairChooseLife commented on src/components/DashBoard/DashBoardItem.tsx
> +        {data.checkDays.includes(today) ? "취소" : "완료하기"}
위에서 이야기 한 내용이긴 한데요, 이 부분만 놓고 보면 `data.checkDays.includes()`에서 checkDays가 체크를 한 날이라는 것인지 체크를 해야 하는 날들이라는 것인지 헷갈립니다.

컴포넌트 이름을 봐도 DashboardItem이란 일반적인 내용이고, 그 안에 "취소" : "완료하기" 가 될 만한 요소가 뭐지? 라고 생각을 하게 만드는데 이것도 코드를 읽는데 소모되는 개발 비용에 들어갈 것 같아요!

2023-04-15 02:35 UTC, greyHairChooseLife commented on src/helpers/calculateDateByWeek.ts
> +export const calculateDateByWeek = (
`calculateDateByWeek` 라는 것은 어떤 값을 계산한다는 것인지 분명하지 않은 것 같습니다. 

export 된다면 밖에서도 사용 할 것인데, 이것도 이 코드를 직접 코딩하는 입장에서 하나의 api잖아요? 그래서 사용이 편리해야 할 텐데, 이름만 보고 가져다 쓰기에는 얘가 뭘 계산해서 뭘 리턴하는 값인지 알 수 없습니다.

2023-04-15 02:35 UTC, greyHairChooseLife commented on src/helpers/getWeekRangeByDate.ts
> +import dayjs from "dayjs";
헬퍼 함수가 여러 파일로 나뉘어 있는데 이것들을 한 파일에 모아두면 어떨까요? 
_이 어플리케이션의 필요에 맞게 dayjs라이브러리를 활용한 헬퍼 함수를 만들어 쓴다._ 라는 공통점으로 의미 상 묶일 것 같습니다.

분리하면 좋은 이유가 생각이 나지 않습니다.

2023-04-15 02:35 UTC, greyHairChooseLife commented on src/hooks/useSelectWeekRange.tsx
> +  };
이 함수를 콜백으로 감싸서 제공하면 훅으로 불러와 사용하는 컴포넌트 입장에서 효율적으로 리렌더링 될 수 있을 것 같습니다.

2023-04-15 12:38 UTC, chadseok commented on src/components/Contoller/index.tsx
> +    <div className={styles.weekController}>
네 @greyHairChooseLife 님. 이 방식은 [css module](https://github.com/css-modules/css-modules) 방식으로 css에서 사용하는 클래스네임을 컴포넌트 내로 한정하는 역할을 합니다. 그래서 범용적인 클래스네임 container, wrapper 등등을 css module에서는 자유롭게 사용이 가능합니다.

2023-04-15 12:39 UTC, chadseok commented on src/components/DashBoard/DashBoardItem.tsx
> +    checkDays: string[];
네. 이부분은 아직 확정된 것이 아니라 일단 임의의 네이밍입니다. 말씀하신 의견도 나중에 구현할 때 고려해 보겠습니다!

2023-04-15 12:43 UTC, chadseok commented on src/hooks/useSelectWeekRange.tsx
> +  };
이게 어떤 의미인지 모르겠는데 예시랑 같이 설명해주실수 있나요?

2023-04-15 12:46 UTC, chadseok commented on src/helpers/getWeekRangeByDate.ts
> +import dayjs from "dayjs";
아 네 @greyHairChooseLife 님. 좋은 제안 감사합니다. 저도 하나로 합치는게 좋은 것 같습니다 .다만 그냥 한 파일에 모아두는 건 아닌 것 같아서 적절한 함수 네이밍과 기준들을 생각해볼께요!

2023-04-15 12:50 UTC, chadseok commented on src/components/Contoller/index.tsx
> +  const { selectedWeekRange, changeWeekRange, isDisabledToClickNextWeek } =
weekRange는 selected없어도 의미를 표현하는데 좋을 것 같습니다. 다만 저는 좀 구체적으로 적는 게 줄이는 것보다 낫다고 생각합니다. 그래서 @greyHairChooseLife 님이 생각하신 `isDisabledToClickNextWeek` 가 button에 들어갈 변수라서 `isLatest`가 그 의미를 다 표현하지 못한다고 생각합니다

2023-04-15 12:52 UTC, chadseok commented on src/helpers/calculateDateByWeek.ts
> +export const calculateDateByWeek = (
아 Date만으로는 정확히 어떤 값을 리턴하는 지 예측하기 힘들 것 같습니다. 좀 더 구체적으로 작성해볼께요

2023-04-15 12:55 UTC, chadseok commented on src/components/DashBoard/DashBoardItem.tsx
> +const today = getToday();
네 저는 일단 개발할 때 실시간으로 today가 바뀌지 않도록 원해서  밖으로 빼내었습니다. @greyHairChooseLife 님이 말씀하신 부분이 어떤 상황인지는 이해해서 habit-tracker 부분을 만들 때 테스트 해보겠습니다

2023-04-15 13:00 UTC, chadseok commented on src/components/DashBoard/DashBoardItem.tsx
> +        {data.checkDays.includes(today) ? "취소" : "완료하기"}
아 네 혹시 @greyHairChooseLife 님이 말씀하신게 의미를 명확하게 하는 래핑 함수를 따로 만든게 좋을 것 같다는 의미인가요? 혹시 예시를 작성해서 설명해주실 수 있나요?

2023-04-15 13:32 UTC, chadseok commented
> * 목데이터는 보통 `root/public/`에다 두더라고요. 아마도 소스코드에 속하지 않아서 그런 것 같습니다. 꼭 그래야 할까 싶기도 한데, 어쨌든 프로젝트의 구조가 조금이라도 간결해 질 수 있을 것 같습니다.

A. 그렇군요. 혹시 알겠습니다!

> * 파일 구조 보여주실 때 인덴트 조금 넣어주시면 더 보기 쉬울 것 같습니다.

A. 넵 혹시 그게 어떤 형태인지 예시를 보여주실 수 있을까요?

> * css파일은 중간에 `.module`을 넣어주셨는데 이것이 어떤 이익을 주는지 알려주시면 감사하겠습니다!

A. 위에도 관련 질문이 있어서 거기에 작성해 두었습니다

> * components 디렉토리의 내부에 위계가 적절하지 않은 것 같습니다. `controller` 또는 `dashboard` 같은 것은 `ProgressBar`보다는 더 상위 컴포넌트 같아서요.

네 이 부분은 커밋 메세지(247764e)에도 있다싶이 ProgressBar가 controller에 속하지 않는다고 판단이 들어 일단 밖으로 빼내었습니다

> * 위 내용은 파일구조 칸 바로 아래 참고 이미지를 보면 더 확실해 지는 것 같습니다. 보면 크게 2개의 컴포넌트로 분리하고 그 구성 컴포넌트들로 표현하셨는데, 여기서 표현 된 위계와 같이 파일 구조를 잡으시면 개발 할 때도, 또 다른 사람이 볼 때도 머릿속에 프로젝트 구조가 딱 그려질 것 같습니다!

위 내용이 어떤 내용인지 알 수 있을까요?

> * rename, remove prefix를 사용하셨는데 저는 refactor라고 달았던 것 같아요. 더 좋은 구분이라고 생각합니다. 다만 일단은 규칙에 없으니 제안하고, 팀  컨벤션으로 정해진 뒤에 써 주셨다면 더 좋았을 것 같습니다!

네. 이 부분은 습관대로 사용하다 보니 말씀해주셔서 prefix에 없는 것을 알게 되었습니다. 네 나중에 제안드릴께요

> * 다만 지워주실 때 다른 테스트용 파일 등도 같이 지워주시면 좋지 않았을까 싶습니다!

test용 파일이 어떤 파일인지 알 수 있을까요? `setupTest.ts`같은 경우에는 나중에 테스트 파일을 넣을 수도 있는데 굳이 삭제할 필요가 없다고 판단이 들었습니다

> * [247764e](https://github.com/wanted-pre-onboarding-side-project/habit-tracker/commit/247764ed58188ca53e62d819e8028e4e7baf3a25) 커밋 메시지로 레퍼런스 달아주실 때 비판적인 의견이나 개선 방향을 새로 이슈를 남기거나 해당 이슈에 댓글로 추가 해 주셨다면 더 좋았을 것 같습니다! 보고서 가봤는데 뭐가 없더라구요!

원래 그렇게 쓰는 용도 인가요? controller부분에 해당하는 기능 개발이 적혀있다 정도로 작성하였습니다. 혹시 이 부분에 대한 문서가 있을 까요?

> * 전반적으로 보면 feat prefix를 달고 있지만 개발 스타일 상 style작업이 같이 포함되는데요, 제목에도 반복해서 등장하구요. 이러면은 style prefix를 달아서 스타일링에 관한 내용을 한눈에 살피자는 의미가 퇴색되는 것 같습니다. `git stash`를 이용하거나 해서.. 뭔가 구분 될 수 있으면 좋겠네요!

아 확실히 그렇네요! 다음 부터 반영해 보겠습니다. 그런데 혹시 feat prefix에 해당하는 기능개발들은 어떤게 있을까요? @greyHairChooseLife 님이 생각하시는 기준이 있을까요?

> * chore prefix 달고 패키지 설치 할 때는 설치 이유, 유용함(?)에 대해 아주 간단히 적어주면 좋을 것 같습니다. 저도 이부분 생각 못했는데 패키지 설치 구분하여 커밋하신 것을 보니까 떠올랐습니다!

A. 음. 적으면 좋을 것 같네요. 다만 이 부분은 저희가 다 논의가 끝난 내용이라 뭔가 이슈 태깅만 하면 될 것같네요

> * 아래와 같은 커밋은 커밋 제목과 내용이 조금 상이 해 보입니다. 코드를 보기 전에는 어떻게 해당 제목과 내용이 연관되는지 이해하기 어려울 것 같습니다.

A. 네 좀 더 자세히 작성해보겠습니다

2023-04-19 11:34 UTC, greyHairChooseLife commented on src/components/Contoller/index.tsx
> +    <div className={styles.weekController}>
아 이게 css파일의 이름에 module이 들어가는거랑 다 함께 의미를 가지는 거였군요.

요걸 적용하면 클래스네임을 어떻게 지어야 하나 하는 문제가 수월하게 해결 되겠네요. 특히 컴포넌트가 많을 때 더 좋겠어요. :+1:

2023-04-19 11:47 UTC, greyHairChooseLife commented on src/components/DashBoard/DashBoardItem.tsx
> +        {data.checkDays.includes(today) ? "취소" : "완료하기"}
래핑 함수를 이야기 한 것이 아니고요, 

위에서 habit 데이터 타입에 checkDays라는 속성이 만약 '체크 한 날짜들'을 담기 위한 것이라면 checkDates라고 하면 더 명확 할 것 같다고 코멘트를 남겼었잖아요? 그렇게 바뀐다면 여기 22번라인도 더 쉽게 읽힐 것이라는 예시가 된다고 생각해서 여기에 코멘트를 한번 더 남겼습니다.

코멘트 남길 때 요런것은 change-request가 아니라 그냥 읽어보고 넘어갈 comment로 달고 싶었는데, 코멘트타입(?)이 이것저것 섞어서는 안되는 것 같아서 그냥 change-request로 했었어요. ㅎㅎ

2023-04-19 12:08 UTC, greyHairChooseLife commented on src/helpers/getWeekRangeByDate.ts
> +import dayjs from "dayjs";
- 함수들의 적절한 네이밍 기준
  함수의 기능에 맞는 이름을 지어주었습니다.

- 무엇을 묶어두어야 하는가? (이것을 말씀 하신 것이 맞겠지요?)
  라이브러리를 쓴다는 이유로 묶어 두는 것은 아니고 용도에 따라 묶습니다. 저 같은 경우엔 자주 사용하는 날짜 값 또는 날짜와 관련된 값을 얻는 용도입니다.

2023-04-19 12:29 UTC, greyHairChooseLife commented on src/hooks/useSelectWeekRange.tsx
> +  };
이 커스텀 훅이 changeWeekRange라는 변수에 어떤 함수를 리턴하고 있잖아요? 만약 해당 함수를 어떤 컴포넌트에서 사용하면 이 커스텀 훅이 리렌더링 되고, 그때 changeWeekRange라는 변수에도 다시 새로운 값이 할당 됩니다. 내용물은 똑같은 함수겠지만요.

changeWeekRange 함수를 사용하는 컴포넌트는 이 커스텀 훅의 상태값은 이용하지는 않을 수도 있는데, 그럴 때 덩달아서 리렌더링이 계속 될 것입니다. 이 같은 점을 useCallback 훅을 이용 해 방지할 수 있어요.

제가 예시를 들기보다는 useCallback 훅에 대해서 찾아보시는 것이 더 수월할 것 같습니다!

2023-04-19 12:52 UTC, greyHairChooseLife commented
@chadseok 

- 꼭 프론트엔드 아니어도 애셋파일 같은 것들은 /src 밖에 두는 것 같아요.
- 아래 경우 처럼 널찍널찍하면 보기가 더 쉬울 것 같다는 말이었습니다.
```
./src/
├── components
│   ├── controller
│   │   ├── Controller.css    
│   │   ├── Controller.tsx    

 ┣ 📂components
 ┃ ┣ 📂Contoller
 ┃ ┃ ┣ ➕Controller.module.css
 ┃ ┃ ┗ ➕index.tsx
```
- >A. 위 내용이 어떤 내용인지 알 수 있을까요?

  PR메시지에 나온 파일 구조와 그 아래 컴포넌트 구성을 나타낸 이미지의 구조가 일치하지 않는다는 말이었습니다.

- 테스트파일은 말씀하신 것이 맞습니다. 기본 설치되어있습니다. 그 외에 vital 어쩌구 하면서 렌더링 효율성을 체크 해 주는 테스트도 있습니다. 테스트 코드에 대한 개발이 예정에 없어서 일단 지웠었어요, 저는. CRA 기본 설치 파일들 정리하셨길래 드린 말씀입니다.

- >A. 원래 그렇게 쓰는 용도 인가요? 저는 controller부분에 해당하는 기능 개발이 적혀있다 정도로 작성하였습니다. 혹시 이 부분에 대한 문서가 있을 까요?

문서는 없습니다. 원래 그런 용도라는 것도 없겠죠(?). 어쨌든 저희 팀에는 없고요. 단지 커밋 메시지 보면서 개발 중에 하시는 이런  생각들이 서로 공유되고 그래서 같이 얘기하게 되면 더 좋게 발전할 수도 있겠다는 생각에 드린 말씀입니다.

- >그런데 혹시 feat prefix에 해당하는 기능개발들은 어떤게 있을까요?

기능 개발은 그냥 전부 feat에 해당한다고 봅니다. 어떤 기능이냐 구분까지 하면 너무 복잡할 것 같아요. 만약에 개발 도중에 기능 별로 feat prefix가 또 나뉘어야 한다는 생각이 든다면 그것은 PR 범위를 너무 넓게 잡은 것을 바로 잡을 일 같아요.


:+1: :+1: :+1: :+1: :+1:

2023-04-23 15:15 UTC, closed without merging