Feature #30
wanted-pre-onboarding-side-project/habit-tracker pull request #42
Opened 2023-04-13 02:50 UTC by jiyeon2

### 1. 무슨 이유로 코드를 추가/변경 했는지

목적 : #30 에서 정의된 기능 구현

작업한 내용
- 조회할 주간 날짜 표시
- 주간 날짜 변경 기능
- 주간 달성률 표시
- 오늘 해야 하는 habit만 Habit today 대시보드에 표시
- Habit today 대시보드에 표시된 habit 완료/되돌리기 기능
- Habit today 대시보드에 표시된 habit description이 긴 경우 자세히 버튼 표시

### 2. 파일 구조와 용도
- css 파일은 `Somecomponent.css`처럼 컴포넌트와 동일한 이름으로 컴포넌트와 동일한 위치에 작성하였습니다

```bash
./src
├── index.tsx   # 컨텍스트 프로바이더 적용하여  App 렌더, dayjs 설정 함수 실행
├── App.tsx     # 전체 컴포넌트 배치
├── components  # App 에 표시할 컴포넌트 보관
│   ├── AddHabitButton.tsx
│   ├── HabitList.tsx
│   ├── PeriodControl.tsx
│   ├── TodayHabits.tsx
│   └── WeeklyProgressDisplay.tsx
├── contexts    # 컨텍스트 프로바이더 보관
│   ├── HabitContextProvider.tsx
│   ├── PeriodProvider.tsx
│   └── hooks   # 컨텍스트 사용하는 커스텀 훅 보관
├── service     
│   ├── memoryHabitService.ts   # 메모리상에 저장된 habit 조회, 수정 기능을 하는 객체
│   └── types.ts   # 여러군데서 사용되는 habit관련 타입 모음
└── setupDayjs.ts   # dayjs 설정 함수
```
![Frame 1](https://user-images.githubusercontent.com/18395475/231633497-3daa91c6-3774-4a60-af6b-c6b0d55a1385.jpg)

### 3. 어떤 부분에 리뷰어가 집중하면 좋을지
- 컨텍스트가 여러개로 쪼개져 있습니다. 렌더링 최적화를 해보려고 value와 action(함수들) 형태로 구분하였습니다

- habit 데이터를 컨텍스트 프로바이더에서 가지고 있는데, 용도에 따라 두 가지로 구분해서 저장했습니다
  - todayHabits : 오늘 해야하는 habit을 저장(조회하는 기간 상관없이 요일로 조회. 오늘이 목요일이면, 목요일에 실행해야 할 habits 목록만 저장), 대시보드에서 사용
  - habitsWithinPeriod : 특정 기간에 해당하는 habits 저장(조회하는 기간이 바뀌면 이 habit 목록도 바뀜). 주간 해빗 목록에서 사용할 예정이었음
 
- habit description이 40자(card 컴포넌트 높이 고려하고 임의로 제가 정한 기준)를 넘어가면 대시보드 카드에서 `...` 말줄임표와 자세히 버튼을 표시합니다

### 4. 관련 스크린샷 or GIF
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/18395475/231626887-e1a79cc9-a911-416b-abec-9f10671cd603.gif)

2023-04-13 08:52 UTC, chadseok requested changes
@jiyeon2 님 구현하시느라 고생하셨습니다. 제가 상태관리에 대한 로직이 어떻게 작동하는 지 질문드리면 내용이 너무 방대해질 것 같아서 이건 나중에 보이스로 들어봤으면 좋겠습니다!

2023-04-13 08:52 UTC, chadseok commented on .prettierrc
@jiyeon2 님 혹시 전체 파일에 대하여 prettier가 적용된 상태인가요? 그 저희가 #31 을 main에다가 merge하고 난 뒤에 적용하면 어떨까요?

2023-04-13 08:52 UTC, chadseok commented on src/App.css
> +  --main-container-width: 70%;
저도 css작성하면서 이런 변수에 대해서 생각해보았는데요 이번 PR이 끝나고  이런 단위나 색깔에 대한 변수들을 논의해보면 좋을 것 같네요.

2023-04-13 08:52 UTC, chadseok commented on src/App.tsx
> +        </section>
semantic tag를 잘 작성해주셨습니다! 저도 이렇게 한 번 적용해 봐야할 것 같아요

2023-04-13 08:52 UTC, chadseok commented on src/contexts/hooks/useHabitContext.tsx
> +};
`useHabitContext.tsx`와 `usePeriodContext.tsx` 에 있는 코드들이 전부 context에서 값을 가져오는 로직으로 파악하였습니다

형태들이 비슷해 보였는데 이런 식으로 래핑하면 어떨까요?

```js
export const useContextWithErrorHandling = (context) => { 
  const value = useContext(context);
     if (!value) {
       throw new Error('Provider 내부에서 사용해주세요');
   }
   return value;
```

저도 이렇게 제안드리기는 했는데 제대로 작동하는 지는 모르겠어서 혹시 @jiyeon2 님이 한번 체크해봐주실수 있나요?

2023-04-13 08:52 UTC, chadseok commented on src/setupDayjs.ts
저도 @jiyeon2 님 처럼 설정을 해봐야겠습니다!! 제 코드에서도 잘 얘기주셔서 감사합니다! 😁

2023-04-13 08:52 UTC, chadseok commented on src/service/memoryHabitService.ts
> +      '우호급 유잣을 럮나 믄디기는 곤랄놔손인 일티뎌 너스친라가 치오 힐됴며 혈푸뎡주긍으로 기쩌 얼캔을 산뇡뇌브에 랗굘누으는 판사아 덴순으니 눈란다 늘잘스봐를 거안음 한신너안멍노에서 겔.',
이런 문장은 어디서 구하신건가요? 재밌네요 😆

2023-04-13 08:52 UTC, chadseok commented on src/components/PeriodControl.tsx
> +      .format('YYYY-MM-DD');
@jiyeon2 님 코드를 보면서 dayjs 라이브러리를 여러 곳에서 직접적으로 코드에 작성하신 것을 보았습니다. 저희가 dayjs에서 다른 라이브러리로 옮길일을 없겠지만 혹시나 dayjs관련 코드를 수정해야 할 때는 산재되어있는 dayjs코드를 찾을 때 많이 힘들 것 같습니다.

그래서 이렇게 구하는 함수는 따로 만들어서 api만 제공하는 형태로 두면 어떨까요? 함수 안에서는 직접적으로 dayjs 코드를 사용하는 것입니다

```js
const startDate = getDateWeekBefore(period.startDate)
const endDate = getDateWeekBefore(period.endDate)

const getDateWeekBefore = (date: Date) => {
  return dayjs(date)
       .subtract(1, 'week')
       .format('YYYY-MM-DD');
}

...
```

2023-04-13 08:52 UTC, chadseok commented on src/index.css
> +}
이렇게 모든 button에 적용되는 단점이 있는 걸로 알고 있어서 scope를 한정시켜보면 어떨까요?

2023-04-13 08:52 UTC, chadseok commented on src/index.tsx
> +setupDayjs();
만약에 저였다면 setupDayjs.ts파일에서 함수를 만들지 않고 그냥 설정을 적용해서  그냥 가져왔을 것 같은데 저도 확실하지는 않아서 제가 적용해보고 말씀드리겠습니다

2023-04-13 10:13 UTC, jiyeon2 commented on .prettierrc
제가 수정한 파일에 한해서는 prettier가 적용된 상태입니다~
#31 을 main에 먼저 적용하고 난 후에
main에 적용된 코드를 제 브랜치로 가져올 생각이었습니다!

#31이 main에 merge된 이후 수정하겠습니다!

2023-04-13 10:14 UTC, jiyeon2 commented on src/App.css
> +  --main-container-width: 70%;
공통으로 사용할 색상 등이 있는 경우
논의해서 정해보면 좋을듯 합니다!

2023-04-13 10:30 UTC, jiyeon2 commented on src/contexts/hooks/useHabitContext.tsx
> +};
오 좋은 아이디어 감사합니다! :+1: :+1: 
아무리 봐도 중복 코드인데 수정하려는 노력을 안했네요..

제네릭을 사용해서 아래와 같이 사용할 수 있을거같아요! 
저는 컴포넌트에서 useContextWithErrorHandling와 컨텍스트 객체 
두 개를 import하는 게 번거로워서 2번처럼 수정해보려고 합니다

혹시 다른 방법을 적용하셨거나 추가 의견이 있다면 알려주세요!!
```ts
export const useContextWithErrorHandling = <T,>(
  context: React.Context<T | null>,
): T => {
  const value = useContext(context);
  if (!value) {
    throw new Error('Provider 내부에서 사용해주세요');
  }
  return value;
};

// 1. 컴포넌트에서 바로 사용
const SomeCompoment = () => {
// const { habitsInWeek } = useHabitsInWeek();
  const { habitsInWeek } = useContextWithErrorHandling(HabitsInWeekContext);
  return <>{habitsInWeek}</>;
};

/// ----------------------------------
// 2. 혹은 커스텀 훅 내부에서 리턴하고
export const useHabitsInWeek = () => { 
  return useContextWithErrorHandling(HabitsInWeekContext);
};
// 그대로 컴포넌트에서 사용
const SomeCompoment = () => {
  const { habitsInWeek } = useHabitsInWeek();
  return <>{habitsInWeek}</>;
};
```

2023-04-13 10:31 UTC, jiyeon2 commented on src/service/memoryHabitService.ts
> +      '우호급 유잣을 럮나 믄디기는 곤랄놔손인 일티뎌 너스친라가 치오 힐됴며 혈푸뎡주긍으로 기쩌 얼캔을 산뇡뇌브에 랗굘누으는 판사아 덴순으니 눈란다 늘잘스봐를 거안음 한신너안멍노에서 겔.',
https://hanipsum.com/ 여기서 무작위로 생성된 문자열을 사용했습니다~

2023-04-13 10:36 UTC, jiyeon2 commented on src/components/PeriodControl.tsx
> +      .format('YYYY-MM-DD');
생각을 못했던 부분인데 알려주셔서 감사합니다~ :+1: 

다른 라이브러리로 교체하거나 사용을 하지 않을 수도 있으니
제안해주신 코드처럼 별도의 함수를 호출하는 형태로 수정해보겠습니다!!

예시 코드도 적어주셔서 감사합니다!

2023-04-13 10:40 UTC, jiyeon2 commented on src/index.css
> +}
기본 button 스타일이 보기 싫어서 
전체 button에 해당 스타일을 적용하려는 의도로 저렇게 작성하긴 했습니다!

말씀해주신대로 저게 단점이 되어
다른 스타일을 적용해야 할 버튼이 있으면 별도의 클래스타 스타일을 적용해서
덮어써야 하는 문제가 있기는 했습니다..

제가 이해를 잘 못해서 그런데
scope를 한정시킨다는게 어떤 의미인가요?
```css
.some-class > button { ... } 
```
이런 식으로 특정 클래스 아래 존재하는 버튼에만 스타일을 지정하는 것을 말씀하신 건가요??

2023-04-13 10:41 UTC, jiyeon2 commented on src/index.tsx
> +setupDayjs();
아 그냥 설정을 적용한 dayjs객체를 리턴하는 형태로 만들어도 되겠네요!
저도 시도해보겠습니다!

2023-04-13 10:54 UTC, chadseok commented on src/index.css
> +}
네 맞습니다!

2023-04-14 02:52 UTC, jiyeon2 commented on src/contexts/hooks/useHabitContext.tsx
> +};
[4413b91](https://github.com/wanted-pre-onboarding-side-project/habit-tracker/pull/42/commits/4413b91a38869389b9f46adc20919e517fc899c4) 커밋에서 2번 예시와 같은 형태로 적용해봤습니다!

2023-04-14 02:59 UTC, jiyeon2 commented on src/index.tsx
> +setupDayjs();
창환님 코드를 참고하여 함수 호출 형태가 아니라 파일만 import 하는 형태로 수정하였습니다 [231c665](https://github.com/wanted-pre-onboarding-side-project/habit-tracker/pull/42/commits/231c66589e9cbb0ea09831545352a291c7872733)

2023-04-14 03:54 UTC, jiyeon2 commented on src/components/PeriodControl.tsx
> +      .format('YYYY-MM-DD');
창환님과 상연님 코드를 참고하여 dayjs를 래핑한 형태로 수정했습니다! [8c7fe25](https://github.com/wanted-pre-onboarding-side-project/habit-tracker/pull/42/commits/8c7fe25cff79cf831145b56c8b8a917bbea8f921)

이 과정에서 불필요하다고 느꼈던 TodayContext (오늘날짜를 dayjs 객체로 제공)와 useToday 훅도 삭제할 수 있었습니다!

2023-04-14 04:13 UTC, jiyeon2 commented on src/index.css
> +}
창환님 제안을 보고 button 태그를 선택자로 쓰기보다
특정 스타일을 적용하는 클래스를 만들어야겠다는 생각이 들었습니다

button 태그를 선택자로 사용하지 않고
.default-button-style 이라는 클래스를 만들어
이 클래스를 제가 원하는 버튼에만 적용하는 형태로 변경했습니다 [16baa04](https://github.com/wanted-pre-onboarding-side-project/habit-tracker/pull/42/commits/16baa04114dfd963bb8552f409294fbfea1ea4e0)

2023-04-15 01:26 UTC, greyHairChooseLife requested changes
## PR 메시지를 보고서..

- types.ts는 다른 컴포넌트나 컨텍스트에서도 사용 할 텐데  service 디렉토리 내부에 있는 것이 의아합니다.
- 몇몇 커밋 prefix가 refactor보단 feat이 맞지 않나 싶습니다. 기존에 있던 코드를 다시 건드리면 리팩터로 두시는 것 같은데, 좀 수정 되더라도 새로운 내용(기능)의 추가라면 feat이 맞다고 생각합니다.

## 컨텍스트 렌더링 관련 의견 요청에 부쳐..

- context providing 할 때 memoization 할 만한 것들을 적절하게 하신 것처럼 보입니다. 
- 다만 내부에 어떤 로직들은 providing을 위한 로직은 아니고 providing 할 값을 얻기 위한 로직으로 보여 분리 할 수 있는 부분이 있을 것 같습니다.

2023-04-15 01:26 UTC, greyHairChooseLife commented on src/App.css
> +  margin: 0 auto;
vh 단위가 여러 화면에 대응하기 좋을 것 같은데, width에만 픽셀을 사용하신 것은 어떤 이유인가요?

2023-04-15 01:26 UTC, greyHairChooseLife commented on src/components/AddHabitButton.tsx
> +const AddHabitButton = (_: AddHabitButtonProps) => {
`(_: Add...)` 이부분은 그냥 `( )`이렇게 비어있으면 안되나요? 사용하는 곳이 없는 것 같아요.

2023-04-15 01:26 UTC, greyHairChooseLife commented on src/components/PeriodControl.tsx
> +      <WeekNextButton />
여기 순서가 다르네요! 저희 디자인 확정한 것 보시면 앞뒤 버튼 두 개 같이 있고, 그 담에 기간 있습니다.

2023-04-15 01:26 UTC, greyHairChooseLife commented on src/components/PeriodControl.tsx
> +    <section className="period">
저는 block요소라는 것을 알리기 위해 보통 `div` 를 썼는데요,

이렇게 `section`으로 나누시면 어떤 차이가 있나요?

2023-04-15 01:26 UTC, greyHairChooseLife commented on src/components/PeriodControl.tsx
> +import usePeriodChange from '../hooks/usePeriodChange';
보면 `someContextAction`도 있고 `someContextChange`도 있는데요, 하나로 통일하거나 아니면 어떤 지연님이 구분하여 사용하는 팁이 있을까요?

2023-04-15 01:26 UTC, greyHairChooseLife commented on src/components/WeeklyProgressDisplay.tsx
이거 데모 영상 보니까 퍼센트 올라가면 전체 bar의 사이즈가 약간 줄더라고요. 고치셨나요 혹시?

2023-04-15 01:26 UTC, greyHairChooseLife commented on src/contexts/HabitContextProvider.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
이 코멘트는 어떤 의미인가요?

2023-04-15 01:26 UTC, greyHairChooseLife commented on src/contexts/HabitContextProvider.tsx
> +  }, [loadHabitsWithinPeriod, loadTodayHabits]);
이 부분은 providing이라는 행위는 아니라서 분리 할 수 있을 것 같습니다. 그러면 useCallback으로 메모리를 차지하지 않을 수도 있을 것 같고요.

그리고 이름 때문에 헷갈린 것일 수도 있는데, HabitsWithinPeriod라는게 결국 이번주 헤빗이죠?  근데 **within**라는 부사는  '수행 기록'에 어울릴 것 같습니다. habits들은 언제나 모두 불러와야 하니까요. 저희가 예를 들어 월~수로 끊는 것이 아니라 1주일 고정 기간이라 그렇다고 생각합니다.

마지막으로 중복 된 데이터가 아닐까요? 그냥 오늘 날짜 찾아서 filter 하면 간단할 것 같습니다. 나누신 이유가 아마 컨텍스트 공급하면서 렌더링을 최적화 하시려고 한 것 같은데, 공급 할 때에만 나눠서 공급하면 되지 싶습니다.

2023-04-15 01:26 UTC, greyHairChooseLife commented on src/contexts/PeriodProvider.tsx
> +interface PeriodActionContextValue {
이 컨텍스트도 타입을 분리하여 모아두는 것은 어떻게 생각하시나요? 그럴만한 가치가 있을까요?

2023-04-15 01:26 UTC, greyHairChooseLife commented on src/contexts/hooks/useContextWithErrorHandling.tsx
아, 이걸 분리 할 수 있겠네요!  그 어떤 provider에 관한 오류 인지 매개변수로 받는 방법도 생각 해 볼 수 있을 것 같습니다!

2023-04-15 01:26 UTC, greyHairChooseLife commented on src/hooks/usePeriodChange.tsx
> +  const isDisabledToMoveNextWeek = isDateBetween(today, {
기왕 렙퍼 함수를 만드신 김에 `isDateBetween()`를 조금 만져주면 

`isDateBetween(today, from, to) 같이 더 간결하게 이용할 수 있을 것 같습니다.

2023-04-15 01:26 UTC, greyHairChooseLife commented on src/hooks/usePeriodChange.tsx
> +  };
함수의 이름은 periodChange인데 하는 일은 `changePeriod`, `loadHabitWithinPeriod` 두 가지인 것이 좋은 생각이 아닌 듯 합니다.

두 함수 또는 두 상태값(habit과 period)의 사이에 어떤 관계(로직)이 있는지 숨겨져 있는 듯 보입니다.

2023-04-15 01:26 UTC, greyHairChooseLife commented on src/hooks/usePeriodChange.tsx
> +    isDisabledToMoveNextWeek,
이것은 상태를 추적할 만한 값이 아닌데 꼭 컨텍스트로 제공해야 할까요?

오늘 날짜는 상수값에 가깝고(매일 변하긴해도 앱에서 그 변화를 추적 할 일이 없음), `period`상태값과 비교하여 화면에 표시 할 수 있을 것 같은데요.

컴포넌트에 표시하냐 마냐의 문제이기 때문에 유틸 함수를 만들어서 컴포넌트에서 period만 가지고 만들어서 사용하면 더 좋을 것 같습니다.

2023-04-15 01:26 UTC, greyHairChooseLife commented on src/hooks/useToggle.tsx
> +  const toggle = useCallback(() => {
이 useCallback이 어떤 경우에 유의미하게 작용하나요?

2023-04-15 01:26 UTC, greyHairChooseLife commented on src/index.tsx
> +      <HabitContextProvider habitService={memoryHabitService}>
`ContextProvider` 컴포넌트를 만들어 쓰면 인자 없이 사용하는것만 봤는데 이런 방법이 또 있네요.

이렇게 index.tsx에서 인자로 넘기는 이유는 무엇인가요?

2023-04-15 01:26 UTC, greyHairChooseLife commented on src/service/memoryHabitService.ts
> +  changeHabitCheck: ({ id, date, value }) => {
리턴 값이 있는 것을 보니 `change...`라고 이름 지은 것과 모순 된 것 같아 보입니다.

`getChanged...` 같은 것이 좋지 않을까요?

2023-04-15 03:19 UTC, jiyeon2 commented on src/App.css
> +  margin: 0 auto;
반응형 대응은 추가 기능이라고 생각해서 고려하지 않았고
width를 px로 설정한 것은 
너비를 1080px 로 고정하기 위해서입니다~

width에 vw단위를 쓴다면
저는 아래처럼 써서 최대 너비를 제한하는 형태로 쓸거같아요

```css
width: 80vw;
max-width: 1080px;
```
vw단위로만 width를 설정하면 
와이드 모니터의 경우 너무 넓어져서 보기 힘들더라고요

2023-04-15 03:22 UTC, jiyeon2 commented on src/components/AddHabitButton.tsx
> +const AddHabitButton = (_: AddHabitButtonProps) => {
AddHabitButton이 header 부분과 dashboard 부분에서 사용되는데
나중에 className만 다르게 전달받아 다르게 표시하려고
props를 받는 형태로 일단 만들어뒀습니다~
개발하다가 필요없어지면 삭제할 생각이었습니다!

2023-04-15 03:55 UTC, jiyeon2 commented on src/components/PeriodControl.tsx
> +import usePeriodChange from '../hooks/usePeriodChange';
usePeriodChange는 내부에서 PeriodContextAction 값을 사용하는(usePeriodAction를 호출하는) 커스텀 훅입니다

이렇게 보니 다 커스텀 훅이라 어떤 동작을 하는지 명확하지 않네요..!

명확한 의도가 있어 저렇게 구분한 것은 아니고
ui에서 로직을 분리하려는 의도로 커스텀훅을 마구 만들다보니
이런 애매한 이름의 훅이 나왔습니다

짚어주신대로 통일하는 방안으로 수정해보겠습니다!

2023-04-15 04:06 UTC, jiyeon2 commented on src/components/PeriodControl.tsx
> +    <section className="period">
`block요소`의 의미가 display: block 요소가 아닌 구획을 의미하는 게 맞다면
저도 구획을 나타내려는 의도로 section태그를 사용했습니다

div와 겉보기에는 큰 차이가 없지만
코드를 읽는 사람이나 검색엔진이 이해하기 쉽도록
<main>, <aside>, <header> 등 의미있는 태그를 사용해봤습니다

저의 경우 
날짜, 진행률, 오늘습관 등 큰 의미단위를 묶는 경우 section을 쓰고(소제목을 붙일수 있을만한 범위)
그 하위범위에서는 div를 사용하였습니다~

2023-04-15 04:24 UTC, greyHairChooseLife commented on src/App.css
> +  margin: 0 auto;
아, 저는 픽셀 단위 쓰신 것이 화면 크기를 고려하지 않은 것 아닌가 했는데 오히려 너무 큰 화면에 대한 대비를 한 부분이였군요. 저는 `vw`를 썼는데, 말씀하신 부분에서 문제가 될 것 같아요.

그리고 이 내용은 반응형 디자인을 할 때 분명히 되어야 할 부분이라 여기서 짚는 것이 옳지 않네요. 

답변 감사합니다!

2023-04-15 04:25 UTC, greyHairChooseLife commented on src/components/AddHabitButton.tsx
> +const AddHabitButton = (_: AddHabitButtonProps) => {
재사용 가능한 컴포넌트로 만들기 위한 부분이셨군요. 이해했습니다!

2023-04-15 04:28 UTC, jiyeon2 commented on src/contexts/HabitContextProvider.tsx
> +  }, [loadHabitsWithinPeriod, loadTodayHabits]);
저의 경우 provider에서 state로 가지고 있는 habit은 
특정 기간에 해당하는 habit만 저장해두려고 within 이라는 이름을 붙인 게 맞습니다!

제가 생각한 구조는 이렇습니다
전체 habit은 로컬스토리지 등 외부에 저장되어 있고
provider에서는 초기 렌더링시 특정기간(이번주)에 해당하는 해빗과 수행 기록을 불러옵니다
따라서 filter 처리는 provider내부가 아닌, 외부에서 데이터를 가져올 때 진행합니다(지금은 memoryHabitService에서 처리하고 있습니다)

게시판 페이지네이션을 예로 들어 말씀드리면
서버에서 전체 글을 불러와서 클라이언트 사이드 페이지네이션으로 처리할 수도 있고,
서버에서 페이지네이션 처리를 해서 현제 페이지에 필요한 데이터만 불러올 수도 있는데

저는 클라이언트 사이드 페이지네이션처럼 내부에서 필터처리를 하지 않고
서버에서 처리된 데이터만 가지고 온 것처럼
현재 필요한 데이터만 provider에 state로 저장하려고 이렇게 코드를 짜봤습니다~

상연님은 클라이언트 사이드 페이지네이션처럼
전체 데이터를 불러오고 클라이언트에서 filter 등 처리를 하는 구조를 생각하신 게 맞을까요?

2023-04-15 04:31 UTC, greyHairChooseLife commented on src/components/PeriodControl.tsx
> +    <section className="period">
아 저는 `display: block`이라는 뜻에서 사용 했습니다.

w3schoole 웹사이트에서도 section은 의미 단위로 묶을만한 것들, 반면 `div`는 최후의 수단으로 사용하라고 하는군요. 말씀하신 바가 정확합니다.

앞으로는 저도 의미 단위로 태그를 group할 때 해당 태그를 쓰도록 하겠습니다!

2023-04-15 04:46 UTC, jiyeon2 commented on src/contexts/HabitContextProvider.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
useEffect 의존성 배열에 값이 없으면 경고를 표시하는 eslint 규칙이 있는데
그 규칙을 바로 아랫줄에 한해서만 끄겠다는 의미의 주석입니다
![image](https://user-images.githubusercontent.com/18395475/232183347-5d0ffd63-273f-42e5-ad43-9052dcdd16c7.png)
vscode에서 제안해주는 자동 수정 중 disable ... for this line을 선택하면
해당 주석이 추가되고 경고 표시가 꺼집니다

최초 렌더링 시에만 loadHabits 함수를 실행하기 위해
의도적으로 의존성 배열을 비운 것이므로 경고를 끄려고 해당 주석을 추가했습니다

useEffect 내에서 loadHabits 함수를 선언하면 
의존성 배열 경고가 뜨지 않을텐데
useEffect 외부에서도 사용해야 해서
일단은 저런 방식으로 처리했습니다~

2023-04-15 04:48 UTC, jiyeon2 commented on src/contexts/PeriodProvider.tsx
> +interface PeriodActionContextValue {
컨텍스트 타입이 다른곳에서 사용되지 않으면 굳이 분리할 필요는 없다고 생각합니다~
저는 외부에서 사용할 일이 없어서 같은 파일에 두었습니다

2023-04-15 04:52 UTC, jiyeon2 commented on src/hooks/usePeriodChange.tsx
> +  };
언급해주신대로 usePeriodChange인데 loadHabitWithinPeriod 작업이 포함된 것은 이상하네요!
컴포넌트에 있던 로직을 커스텀 훅으로 떼어내는 것만 신경써서 인지하지 못했습니다!

period 에 따라 habit을 가져오는 구조라서 
둘 사이에 관계가 있는 것은 맞습니다!
그게 명확하게 보이도록 작성하지 못했네요.. 좀 더 고민해보고 수정하겠습니다!

2023-04-15 04:55 UTC, jiyeon2 commented on src/hooks/usePeriodChange.tsx
> +    isDisabledToMoveNextWeek,
> 컴포넌트에 표시하냐 마냐의 문제이기 때문에 유틸 함수를 만들어서 컴포넌트에서 period만 가지고 만들어서 사용하면 더 좋을 것 같습니다.

좋은 의견 감사합니다! 여기서 분리된 유틸 함수를 만드는 건 생각을 못했어요

2023-04-15 04:58 UTC, jiyeon2 commented on src/hooks/useToggle.tsx
> +  const toggle = useCallback(() => {
useToggle 훅을 호출하는 컴포넌트에서 defaultValue 값이 바뀌면
useToggle 함수도 다시 실행되어 toggle 함수가 바뀔거라고 생각해서 useCallback 함수로 감쌌습니다
하지만 실제로 그런지는 확실하지 않습니다..!

2023-04-15 05:06 UTC, jiyeon2 commented on src/index.tsx
> +      <HabitContextProvider habitService={memoryHabitService}>
HabitContextProvider 는 불러온 habits를 컴포넌트에 전달하거나, 컴포넌트에 필요한 핸들러 함수를 전달합니다

어디서 habits를 어떻게 받아올지에 대한 세부 구현사항은 habitSerive에서 처리합니다

지금은 앱을 실행한 메모리에 habits를 저장한 형태인데
나중에 로컬스토리지나 다른 곳에 habits를 저장하고 불러오는 형태로 변경하기 쉽도록 인자로 받아오게 작성했습니다~

2023-04-15 05:08 UTC, greyHairChooseLife commented on src/components/PeriodControl.tsx
> +import usePeriodChange from '../hooks/usePeriodChange';
그러네요. 
`usePeriodAction` 요것은 오직 `usePeriodChange` 훅 안에서 쓰이기 위한 것이였네요.

커스텀 훅을 만들기 위한 커스텀 훅이라는 생각을 제가 해 본 적이 없어서 이해가 더 어려웠던 듯 합니다. 

다만 이름도 이름인데 지금 구조를 보면,

```
├── context
│   ├── provider
│   │   └── contextProving
│   └── hook (exporting context)
│        └── useContext
├── hook
│   ├── usePeriodChangeHook
```

와 같은데요,

`usePeriodChangeHook`을 컨텍스트 프로바이더가 받아서 쓰는 방식(반대 방향)으로 로직이 흐르면 이해하기 한결 쉬울 것 같습니다.

제가 컨텍스트 사용해본 경험이 거의 지금 처음이라 그럴지 몰라도.. 보통 컴포넌트가 컨텍스트에서 받아다가 액션이든 상태값이든 사용하지, 커스텀 훅이 컨텍스트로 제공 되는 값을 활용하고, 그 커스텀 훅을 컴포넌트가 쓰지는 않을 것 같습니다.

2023-04-15 05:11 UTC, jiyeon2 commented on src/service/memoryHabitService.ts
> +  changeHabitCheck: ({ id, date, value }) => {
habits.map() 의 콜백함수 내부에 있는 return 때문에 헷갈려 보이는데
memoryHabitSerivce는 로컬스토리지를 사용하면 삭제할 생각이어서 코드를 보기 좋게 작성하지 못했습니다.. 

changeHabitCheck 은 리턴값이 없습니다~
`changeHabitCheck: ({ id, date, value }: HabitCheckChangeDataType) => void;`
형태로 내부 check 배열만 수정합니다

2023-04-15 05:25 UTC, greyHairChooseLife commented on src/hooks/useToggle.tsx
> +  const toggle = useCallback(() => {
useState의 default value가 바뀐다는 말은 오류인 것 같습니다.
디폴트 값은 맨 처음 렌더링 될 때에만 사용하고 이후에는 사용하지 않습니다.

그러니까 이 커스텀 훅을 사용하는 컴포넌트가 아무리 리-렌더링 되더라도 디폴트 값은 변하든 말든 리액트 입장에서 개의치 않는다고 알고 있습니다. 오로지 setter로 새로운 값을 전달해야만 그 컴포넌트에서 불려진 인스턴스에서 상태값이 바뀌고 리렌더링이 될거에요.

제가 질문한게 저는 잘 안떠올라서 그랬는데 지금 코멘트 보고 찬찬히 생각해보니까, 하신 말씀이 딱 맞는 것 같습니다. 근데 toggle함수 실행 시 이 커스텀 훅이 리렌더링 되는 이유는 위에서 말씀 드린 바와 같이 defaultValue때문이 아니라 toggle함수로 인해 value상태값이 바뀌기 때문이겠습니다!

2023-04-15 07:18 UTC, greyHairChooseLife commented on src/index.tsx
> +      <HabitContextProvider habitService={memoryHabitService}>
아, 그러니까 habit데이터를 CRUD 하는 역할을 하는 객체를 생성하신 거네요. 테스트 데이터를 하드코딩으로 입력 해 둬서 임시로 사용했지만, 앞으로 이 객체가 클래스가 되어서 상태값을 가지게 되는 역할을 하겠네요.

이 부분은 창환님 합류 전에도 같은 방식으로 하셨었고, 그때 드렸던 질문을 조금 더 구체적으로 드려 볼게요.

**리액트 내장 훅 대신 new Class instance를 사용해서 선택해서 얻을 수 있는 이점이 어떤 것이 있나요?**

제가 둘의 차이에 대해 검색도 해 보고 곰곰이 생각 해 봤는데요, 가장 큰 것은 **함수형 프로그래밍 vs 객체지향 프로그래밍**의 차이가 있을 것 같습니다. 그리고 이 점 때문에 리액트 프로젝트에서는 기본적으로 함수형 컴포넌트와 훅을 사용하고, 예외적으로 클래스 인스턴스를 쓸 수 있을 것 같습니다.

### 근거 1.

일단 리액트 함수형 컴포넌트와 훅은 함수형 프로그래밍의 구현이라고 볼 수 있습니다. 왜냐면 상태를 생성하는 useState와 useReducer가 클로져를 활용해서 데이터를 private하게 관리하기 때문입니다. 개발 하는 입장에서 불변성을 유지 하는 것이 당장은 답답하지만, 그런 규칙 아래에서 안전하고 예측 가능한 프로그래밍이 가능합니다.

반면에 클래스는 훨씬 자유롭습니다. 그 안에 상태값으로 쓸 변수들을 선언하고 할당하여 마음껏 쓸 수 있습니다. 그러나 자유로운 만큼 데이터의 관리는 개발자의 능력에 달려 있습니다. 실수 할 여지가 있는 것과 없는 것의 차이라고 할 수 있습니다.

물론 클래스 내에서 불변성을 잘 유지하기 위한 코드를 작성 할 수 있지만, 이미 잘 만들어져 공식적으로 지원하는 리액트 훅이나 널리 이용되는 리덕스, 리코일 같은 서드파티 라이브러리가 첫번째 선택이어야 한다고 생각합니다.

### 덧붙이는 말

관련하여 저도 도대체 차이가 뭘까 하면서 지난 인턴쉽의 멘토님이 클래스 문법을 활용하는 것을 돌아봤어요. 거기에서는 클래스가 데이터를 전달만 할 뿐입니다. 데이터를 가공하거나 직접 저장하여 관리하지 않습니다.

이 경우 데이터를 올바르게 관리하는 부담이 전혀 없습니다. 왜냐면 그것은 백엔드의 역할이니까요.

제 의견을 어떻게 생각하실까요?

2023-04-15 07:35 UTC, greyHairChooseLife commented on src/service/memoryHabitService.ts
> +  changeHabitCheck: ({ id, date, value }) => {
useState의 default value가 바뀐다는 말은 오류인 것 같습니다.
디폴트 값은 맨 처음 렌더링 될 때에만 사용하고 이후에는 사용하지 않습니다.

그러니까 이 커스텀 훅을 사용하는 컴포넌트가 아무리 리-렌더링 되더라도 디폴트 값은 변하든 말든 리액트 입장에서 개의치 않는다고 알고 있습니다. 오로지 setter로 새로운 값을 전달해야만 그 컴포넌트에서 불려진 인스턴스에서 상태값이 바뀌고 리렌더링이 될거에요.

제가 질문한게 저는 잘 안떠올라서 그랬는데 지금 코멘트 보고 찬찬히 생가해보니까, 만약 어떤 컴포넌트에서 이 toggle을 받았는데 이것을 하위 컴포넌트에게 props로 전달 하고, 전달 받은 컴포넌트에서 toggle 함수를 실행해도 자기자신이 리렌더링 되지 않는다는 장점이 있겠네요.

2023-04-15 07:54 UTC, greyHairChooseLife commented on src/contexts/HabitContextProvider.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
경고가 뜨면 경고를 죽인다는 것이 좋은 접근이 아닌 것 같습니다. 자동차 엔진 경고등이 들어왔는데 경고등을 꺼버리는 경우랄까요?

loadHabits 함수는 내부적으로 2개 함수를 실행하고, 그 중 1개는 금주의 habits를 리턴합니다. **금주**이기 때문에 이름지으신 대로 period 값을 의존성 배열로 갖고 있는 것을 볼 수 있습니다.(같은파일 callback하신 부분)

같은 역할을 최초 그리고 이후 상태의 변화(의존하는 것은period가 되겠죠)에 따라 추적 하기 위해 각각, `useEffect`와 `service 객체의 메소드들을 실행하는 이벤트 헨들러에 묶어서` 사용하신 것 같습니다.

최신 데이터(추가되거나 업데이트 된 habit들)를 상태값에 담아 유지하기 위한 고육지책으로 보이는데, 좋은 방법이 아닌 것 같아요.

다만 그래서 어느 부분 설계가 잘못 된 것인지, 어떻게 쉽고 간결한 논리 구조로 개선 할 수 있는지를 파악하기가 어려워서 제안을 드릴 수가 없네요 :cry: 

제 의견에 어떻게 생각하시나요?

2023-04-15 08:04 UTC, greyHairChooseLife commented on src/contexts/HabitContextProvider.tsx
> +  }, [loadHabitsWithinPeriod, loadTodayHabits]);
### 1.

아, 그렇군요. 저랑 애초에 habit의 타입을 다르게 두고 하다 보니 제가 오해를 했었네요.

저는 이 코멘트에서 __수행기록__을 제외한 habit정보에 대해서만 생각하고 말 했습니다. __수행기록__에 관해서는 저도 필요한 만큼 가져오는 방식을 예상하고 있습니다. 전부 가져오거나, 하루만 가져오거나, 한 주만 가져오거나 개발하려는 기능에 맞춰 다양한 모습을 할 수 있다고 생각합니다.

다만 수행기록을 관리하는 것은 이번 PR의 영역 밖이라고 생각해서, 이 부분 표현하신 거라고 생각을 못했습니다.

### 2.

한편 
```
  const loadHabits = useCallback(() => {
    loadTodayHabits();
    loadHabitsWithinPeriod();
  }, [loadHabitsWithinPeriod, loadTodayHabits]);
```

이 함수와 내부의 2개 함수를 모두 수행하여 리턴하는 커스텀 훅을 만들어서 콜백의 부담을 줄이는 것은 어떻게 생각하시나요?

2023-04-15 11:31 UTC, jiyeon2 commented on src/components/WeeklyProgressDisplay.tsx
[dc6fcaf](https://github.com/wanted-pre-onboarding-side-project/habit-tracker/pull/42/commits/dc6fcafc8696482e16260cdd2cf6e72c34f85470) 에서 막대 부분과 숫자 표시 부분 width를 고정하여 
레이아웃 변동이 생기지 않도록 수정하였습니다~

2023-04-15 12:23 UTC, jiyeon2 commented on src/index.tsx
> +      <HabitContextProvider habitService={memoryHabitService}>
의견을 자세하게 남겨주셔서 감사합니다~

지난 pr 리뷰(#14)에서도
**커스텀 훅 대신 클래스를 통해 전역 상태를 관리하는 이유** 를 여쭤보셨는데요

**제가 작성했던 코드에서 provider가 주입받는 클래스 인스턴스는 전역상태 관리용이 아니다**라는 답변을 남기며
클래스 인스턴스에서 상태를 가지고 있을 필요가 없다는 사실을 인지하여
내부 변수를 삭제한 형태로 수정한 바 있습니다 (지난 리뷰 수정 커밋 [185c976](https://github.com/wanted-pre-onboarding-side-project/habit-tracker/pull/14/commits/185c9765d09e1cb21494c3f1f0ace6a4258df283))

지난 리뷰에서 수정한 커밋을 보면
덧붙이는 말에서 언급하신 내용처럼 클래스 인스턴스가 데이터를 **전달(리액트 프로바이더 <=> 로컬스토리지)하는 역할**을 하고 있습니다
(로컬스토리지는 리액트 앱의 전역상태 저장이 아닌, 앱이 종료되어도 기존 데이터를 저장하기 위한 외부 저장소로 사용했습니다)

현재 코드에서도 이전 리뷰에서 수정한 코드처럼 
클래스 내부에서는 상태를 가지지 않고 
habit 데이터를 CRUD하는 역할을 하는 객체가 될 예정이었습니다
따라서 아래 인용한 상연님의 추측은 제 계획과는 다릅니다

> 테스트 데이터를 하드코딩으로 입력 해 둬서 임시로 사용했지만, 앞으로 이 객체가 클래스가 되어서 상태값을 가지게 되는 역할을 하겠네요.

> 리액트 내장 훅 대신 new Class instance를 사용해서 선택해서 얻을 수 있는 이점이 어떤 것이 있나요?

위 문장으로 보아 상연님의 질문은
'제가 사용한 클래스 인스턴스는 전역상태관리를 하는 객체다'라는 전제를 깔고,
**리액트 훅이 아닌 클래스 인스턴스에서 전역상태를 가지고 있는/ 혹은 전역상태를 관리하는 것의 이점이 무엇이냐**를 묻고 있다고 이해했습니다 
(만약 제가 또 잘못 이해했다면 번거로우시겠지만 한번 더 설명 부탁드립니다..)

저는 전역상태를 관리할 용도로 클래스 인스턴스를 사용하지 않았으므로, 
전역상태 관리 시 리액트 훅이 아닌 클래스 인스턴스를 사용하는 이점에 대한 답변은 드리기 어렵습니다(상연님이 남겨주신 링크를 보면 이점은 없을 것으로 생각합니다)

제 리액트 앱에서 사용할 전역상태라고 부를 수 있는 habits는 HabitContextProvider에서 useState로 가지고 있습니다

memoryHabitService 파일에 존재하는 habits 변수는 리액트 앱의 전역상태 관리용 객체가 아닙니다(이름을 헷갈리게 지었네요..)
로컬스토리지를 사용하지 않은 상태에서 '외부 저장소 역할'을 하는 임시 변수입니다 (로컬스토리지를 외부저장소로 사용하는 habitService 파일을 만들고 나면 memoryHaitService파일 자체를 삭제할 생각이었습니다)

리액트에서 전역상태를 관리할 때 외부 전역객체를 사용하는 것보다
리액트에서 지원하는 api나 이미 잘 구성된 서드파티 라이브러리를 사용하는 것이 좋다는 상연님의 의견에는 저도 찬성합니다!

2023-04-15 12:52 UTC, jiyeon2 commented on src/contexts/HabitContextProvider.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
맞습니다!! 로직을 개선하지 않고 경고를 끄는 방식은 저도 문제가 있다고 생각합니다!
제가 만들고 있지만 저도 머릿속에서 정리가 안되어 개선하지 못했습니다.. 좀 더 진행해보면서 좋은 방법이 생각나면 수정해보겠습니다!!

2023-04-16 16:59 UTC, jiyeon2 commented on src/contexts/HabitContextProvider.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
HabitContextProvider 마운트 시 한번만 실행될 useEffect 함수에서 의존성 배열에 들어갈 값을 제거하여
주석으로 경고를 끄고 있는 형태를 수정했습니다

1. HabitContextProvider 내부에서 useReducer의 dispatch 사용  : dispatch 는 바뀌지 않으므로 의존성배열에 포함될 필요가 없음 [806f6b9](https://github.com/wanted-pre-onboarding-side-project/habit-tracker/pull/42/commits/806f6b9c65c74f5b9e2b1e18368d19337a2c068e)
2. loadAllHabits 액션 함수에서 period 인자를 옵셔널로 수정 : period 값이 주어지지 않으면 이번주를 기본값으로 사용 [aec4952](https://github.com/wanted-pre-onboarding-side-project/habit-tracker/pull/42/commits/aec49528b444f06c3a2cf1defcf7141a4f4c57cb)

불필요한 의존성배열을 없앨 수 있었고
HabitContextProvider 내부 코드 가독성을 올리는 효과를 얻었습니다!

2023-04-16 17:03 UTC, jiyeon2 commented on src/contexts/HabitContextProvider.tsx
> +  }, [loadHabitsWithinPeriod, loadTodayHabits]);
useReducer를 사용하는 방식으로 변경하는 과정에서
loadHabits 동작을 reducer의 case: 'loadAllHabits' 부분으로 분리하였습니다 [806f6b9](https://github.com/wanted-pre-onboarding-side-project/habit-tracker/pull/42/commits/806f6b9c65c74f5b9e2b1e18368d19337a2c068e)

프로바이더 내부에서는 ` dispatch({ type: 'loadAllHabits', period });` 처럼 호출하여 
useCallback함수를 사용하지 않는 형태로 수정하였습니다

2023-04-16 17:10 UTC, jiyeon2 commented on src/index.tsx
> +      <HabitContextProvider habitService={memoryHabitService}>
[806f6b9](https://github.com/wanted-pre-onboarding-side-project/habit-tracker/pull/42/commits/806f6b9c65c74f5b9e2b1e18368d19337a2c068e) 에서 reducer가 habitService를 이용하는 형태로 수정했습니다

이런 구조면 리액트 상태관리는 리액트 훅(useReducer)으로 하고 있고
클래스 인스턴스는 외부 저장소에 데이터 반영 및 불러오기 역할을 하고 있다는 게 조금 더 명확하게 보일까요..?

2023-04-19 10:18 UTC, greyHairChooseLife commented on src/contexts/HabitContextProvider.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
문제를 잘 해결 하신 것 같습니다. 저는 전혀 생각지 못한 방법으로요.

useReducer 훅의 장점이 컴포넌트와 상태 관리의 분리라고 생각은 하지만 저는 물리적인 분리만 생각 했었거든요. 근데 이렇게 사용하신 것을 보니까 상태 그 자체와 상태를 업데이트하는 리듀서가 분리되어서 각 컴포넌트에 공급 될 때에도 효율적이네요.

덕분에 저도 잘 배웁니다. :+1:

2023-04-19 10:22 UTC, greyHairChooseLife commented on src/contexts/HabitContextProvider.tsx
> +  }, [loadHabitsWithinPeriod, loadTodayHabits]);
여러가지 문제를 같이 고민해서 해결책을 찾은 것 다시 한번 칭찬해요. :+1:

2023-04-19 11:12 UTC, greyHairChooseLife commented on src/index.tsx
> +      <HabitContextProvider habitService={memoryHabitService}>
제가 어떤 의문을 가졌는지, 지연님이 이해하신 하신 바가 딱 맞습니다.

그러나 https://github.com/wanted-pre-onboarding-side-project/habit-tracker/pull/42/commits/806f6b9c65c74f5b9e2b1e18368d19337a2c068e 커밋 이후에도 여전히 상태 관리를 클래스에서 하고 있으신 것으로 보입니다.

저는 상태 관리란 상태 값의 저장과 CRUD가 포함 되는 모든 코드라고 생각해요. 

작성하신 class를 보면 addHabit, changeHabitCheck, 그리고 몇 가지 종류의 읽기가 있습니다. 이 중에서 addHabit을 보면 새로운 habit 하나를 만들어내고 있습니다. 또 changeHAbitCheck를 보면 기존 habit을 수정하고 있습니다.

상태관리를 useReducer로 하고있다 말 하기 위해서는, 이렇게 새로운 habit을 만들고, 또 기존 habit을 수정하는 것을 reducer에서 해야 하는 것 같습니다. 또는 useState를 사용 한다면 setter함수를 이용하고요.

도식화 해 보자면,
:o: 상태값 변경 :point_right: setState 또는 dispatch(reducer)로 새로운 상태값(스냅샷) :point_right: 새로운 상태값을 갖다가 로컬 스토리지 등에 반영
:x: 상태값 변경 :point_right: 임의 객체 생성 또는 수정하여 로컬 스토리지에 반영 :point_right: 로컬 스토리지에서 값 꺼내와서 내 상태에 넣어주기

2023-04-23 16:02 UTC, closed without merging