Feature #49
wanted-pre-onboarding-side-project/habit-tracker pull request #50
Opened 2023-04-24 07:22 UTC by chadseok

2023-04-27 06:59 UTC, jiyeon2 commented on src/components/HabitList/HabitList.module.css
> +  pointer-events: none;
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/18395475/234783632-a06e087f-5ad9-43b9-98fc-fc02736f5a23.gif)

HabitList.tsx 에서 button에 전달되는 스타일인데
css의 ponter-event로만 클릭을 막아놔서 
탭으로 포커스 이동시 클릭이 가능합니다

css 외에 HabitList.tsx에서 disabled값을 주거나 type에 따라 렌더링을 하지 않는 등 추가 방법이 필요해보여요!

2023-04-27 07:13 UTC, jiyeon2 commented on src/components/HabitList/useHabitList.tsx
> +  const getTypeOfButton = (item: Habit, day: (typeof weekData)[number]) => {
```ts

// getTypeOfButton 리턴값이 undefined가 되는 경우가 존재
item.recordDates = [
{'2023-04-20': 'inactive'},
];
day.date = '2023-03-03';

return item.recordedDates[day.date]; // undefined
```
getTypeOfButton의 리턴값이 undefined가 되는 경우가 존재하지만
```ts
recordedDates : { [key: string] : 'inactive' | 'completed' }
day.date : string
```
타입 정의상으로는 항상 inactive, completed가 나오므로 
getTypeOfButton의 리턴값이 'future' | 'inactive' | 'completed' 으로 추론됩니다

undefined가 리턴되는 경우를 의도하신거라면 
해당 함수의 리턴값에 명시하는 게 좋지 않을까 생각이 들었습니다

2023-04-27 07:19 UTC, jiyeon2 commented on src/components/Modal/Modal.tsx
> +          <h1>습관 추가하기</h1>
props로 habitToUpdate 가 주어지는 경우에도 '추가하기'라고 표시돼요~
수정하기 버튼처럼 habitToUpdate값에 따라 다르게 표시하면 좋겠습니다

2023-04-27 07:46 UTC, jiyeon2 commented on src/components/Modal/useModal.tsx
Modal  컴포넌트의 로직이 모두 한군데 모여있는데 
제가 보기에는 역할이 다른데 한군데 묶여있는 느낌이에요

input을 관리, dispatch 로직 두 개의 훅으로 분리하면 어떨까 생각했는데
창환님은 어떠신가요??

```tsx
const Modal = () => {
 const {name, changeName, description, changeDescription,... reset} = useModalInputs();
 const {addHabit, editHabit, closeModal} = useModalActions();

return (
  <button onClick={() => addHabit(name, description, days)}>추가</button>
)
}

```

2023-04-27 07:52 UTC, jiyeon2 commented on src/contexts/HabitContextProvider.tsx
> +  localStorage.setItem('HABIT_DATA', JSON.stringify(state));
localStorage.setItem 하는 부분이 여기뿐인데
state가 바뀌면 HabitProvider가 다시 실행되면서 
localStorage.setItem()이 실행되는 건가요??

2023-04-27 07:54 UTC, chadseok commented on src/components/HabitList/HabitList.module.css
> +  pointer-events: none;
아 @jiyeon2 님. 직접 clone하셔서 테스트 해주신 건가요? 테스트 해주셔서 감사합니다!

저도 탭으로 이동시 클릭이 가능하다는 사실은 몰랐습니다! disabled값을 주거나 아예 접근을 하지 못하도록 해야겠네요!

2023-04-27 07:57 UTC, jiyeon2 commented on src/lib/utils/dateUtils.ts
> +export const getFormattedString = (date: Date, formatString?: string) => {
'YYYY-MM-DD' 가 기본값이라면
```ts
const getFormattedString = (date: Date, formatString = 'YYYY-MM-DD') => {
  return dayjs(date).format(formatString);
}
```
로 써도 괜찮을거같아요!

2023-04-27 07:58 UTC, chadseok commented on src/components/HabitList/useHabitList.tsx
> +  const getTypeOfButton = (item: Habit, day: (typeof weekData)[number]) => {
네. 저도 처음에는 undefined을 명시하였는데 그렇게 작성하다 보니 삼항연산자가 너무 길어져서 알아보기가 힘들지 않을 까 걱정해서 뺐습니다. 의견을 주신것을 생각해보니 @jiyeon2 님이 말씀하신 것도 맞는 말씀이라고 생각이 듭니다. 

@jiyeon2 님은 코드를 파악하는 데 힘드시지는 않으셨나요?

2023-04-27 08:00 UTC, chadseok commented on src/components/Modal/Modal.tsx
> +          <h1>습관 추가하기</h1>
네 맞습니다! 저도 고쳐할 리스트에만 넣어 놓고 시간이 안되서 못 고쳤네요. 🥲 다시 알려주셔서 감사합니다!

2023-04-27 08:04 UTC, chadseok commented on src/contexts/HabitContextProvider.tsx
> +  localStorage.setItem('HABIT_DATA', JSON.stringify(state));
넵 맞습니다. 기존의 context api와 useReducer을 활용한 경우에 state가 바뀔때마다 적용할려고 하니까 로직을 넣을 장소가 저기 밖에 없더라구요. @jiyeon2 님은 어떻게 구현하셨는지 여쭤봐도 될까요?

2023-04-27 08:04 UTC, jiyeon2 commented on src/components/HabitList/useHabitList.tsx
> +    }
이부분은 if문에다 삼항연산자 조건이 길어서 이해하기 어려웠습니다..

현재 주간이 아닐때
(habit의 routineDays에 오늘 요일이 포함되거나 || habit recordedDate에 오늘 날짜가 없다(체크하지 않았다) )
&& 오늘보다 뒤의 날짜면 future 타입이다

이 로직이 맞나요?? 

아래처럼 하면 if문 블록의 길이가 줄거같기는 한데
더 좋은 방법이 떠오르지 않네요~~
```ts
if (!isSameWeek(seledtedDate, nowDate)) return item.recordedDates[day.date];
return 삼항연산자...
```

2023-04-27 08:08 UTC, jiyeon2 commented on src/components/Dashboard/HabitCard/HabitCard.module.css
> +  composes: description;
이렇게 쓰는 건 처음봤는데 css-module에서 제공하는 기능인가 보네요
description 클래스 속성을 그대로 가져오는 건가요??

2023-04-27 08:08 UTC, chadseok commented on src/lib/utils/dateUtils.ts
> +export const getFormattedString = (date: Date, formatString?: string) => {
네 저는 default parameter를 적용할 때 옆에 타입도 적어줘야 하면 매개변수 쪽이 길어지니까 따로 작성해왔던 것 같습니다. @jiyeon2 님은 default paramter를 적용하시는 게 좀 더 알아보기 쉬우신가요?

2023-04-27 08:12 UTC, chadseok commented on src/components/Dashboard/HabitCard/HabitCard.module.css
> +  composes: description;
네 그 기능을 사용하면 둘의 classname이 둘다 적용됩니다

<img width="688" alt="스크린샷 2023-04-27 오후 5 11 32" src="https://user-images.githubusercontent.com/83488329/234800908-371af1f1-0588-46a0-98bc-5a79e62942a0.png">

2023-04-27 08:22 UTC, chadseok commented on src/components/HabitList/useHabitList.tsx
> +    }
네 저도 그 삼항연산자 로직 부분이 고민이 되네요.. 저도 처음에는 undefinded를 포함해서 이렇게 작성했습니다

```ts
 return item.routineDays.includes(day.label) ||
         item.recordedDates[day.date]
         ? dayjs(day.date).isSameOrBefore(now, 'day')
           ? item.recordedDates[day.date] === 'inactive'
             ? 'inactive'
             : 'completed'
           : 'future'
         : undefined;
     }

 return item.recordedDates[day.date]
       ? item.recordedDates[day.date] === 'inactive'
         ? 'inactive'
         : 'completed'
       : undefined;
   };
```

early return 부분은 작성하면서 고려 해보겠습니다

2023-04-27 08:22 UTC, jiyeon2 requested changes, later dismissed
컴포넌트별로 폴더를 따로 만드신 걸 보니 어떤 컴포넌트가 존재하는지 한눈에 알 수 있어 좋네요!
저는 컴포넌트 기존 구조 그대로  SomComponent/parts 를 사용해서 폴더 하나를 더 들어가야 모든 컴포넌트를 확인할 수 있습니다

디자인에도 신경쓰셔서 퀄리티가 높아보여요! :+1: 
같은 시간 동안 작업했는데 결과물이 이렇게 다르니 부끄럽습니다

HabitProvider내부에서 useReducer를 사용하셔서 코드가 간결하고
reducer 함수로 로직이 잘 분리되어 있어 이해하기 좋았습니다!

ModalContext의 경우 저도 모달 내부 요소를 갈아끼우는 형태를 생각했는데
창환님처럼 Portal컴포넌트를 만들 생각을 못해서 컨텍스트를 사용하지 못했습니다..
모달을 열 때 toggleModal, changeModalComponent 두가지 함수를 항상 같이 호출해야 하는데
거기에 대한 불편함은 없으셨나요?

제가 렌더링 최적화에 대해 잘 알지 못해 
어느 부분에서 신경을 쓰셨는지 알아보지 못했습니다.. 
고민해서 렌더링 최적화를 적용하셨던 부분이 있으시면 알려주실 수 있을까요?

2023-04-27 08:24 UTC, jiyeon2 commented on src/components/HabitList/HabitList.module.css
> +  pointer-events: none;
네 직접 동작을 보고싶어서 클론해서 확인했습니다~
직접 보니 애니메이션도 적용되어 있고 ui가 정말 예뻐요~~

2023-04-27 08:28 UTC, jiyeon2 commented on src/components/HabitList/useHabitList.tsx
> +  const getTypeOfButton = (item: Habit, day: (typeof weekData)[number]) => {
getTypeOfButton을 만들지 않은 사람이 저 함수를 가져다 쓰기만 한다면
리턴타입에 undefined가 없어서 잘못된 로직을 만들 수도 있을거같아서
리턴타입은 바르게 써주는 게 좋을거같아요!

코드 파악하는 경우
몇몇 부분은 바로 알아보기는 힘들었지만
같은 기능을 만들다보니 정확히는 몰라도 이게 무슨 기능을 위한 코드구나~ 정도로는 이해할 수 있었습니다!

2023-04-27 08:30 UTC, jiyeon2 commented on src/contexts/HabitContextProvider.tsx
> +  localStorage.setItem('HABIT_DATA', JSON.stringify(state));
저는 로컬스토리지 부분을 구현하지 못했습니다..
만약 창환님 코드 기준이면 지난번 상연님이 말씀해주신대로
```
useEffect(() => {
  localStorage.setItem('HABIT_DATA', JSON.stringify(state));
},[state])
```
useEffect훅으로 state가 바뀔때마다 실행하는 형태로 시도해볼거 같아요!

2023-04-27 08:31 UTC, jiyeon2 commented on src/lib/utils/dateUtils.ts
> +export const getFormattedString = (date: Date, formatString?: string) => {
함수 블록까지 보지 않아도
인자 부분만 보고도 바로 기본값을 알 수 있어서 좋다고 생각합니다~

2023-04-27 08:32 UTC, jiyeon2 commented on src/components/Dashboard/HabitCard/HabitCard.module.css
> +  composes: description;
오 클래스가 둘 다 적용되는군요! 알려주셔서 감사합니다~

2023-04-27 09:18 UTC, chadseok commented on src/components/Modal/useModal.tsx
오 좋은 분리라고 생각합니다! hooks를 또 나누는 것은 생각 안해봤는데 한 번 프로젝트에 적용시켜 보고 테스트 해봐야 겠네요!

2023-04-27 09:28 UTC, chadseok commented
@jiyeon2 님 먼저 칭찬 감사드립니다! 😃

Modal 관련해서 `toggleModal`과 `changeModalComponent`를 항상 같이 import해서 사용해야 한다는 점은 저도 불편하다고 느끼고 있었습니다. 저도 @jiyeon2 님 처럼 ModalContext를 삭제하면 불편함을 없앨 것 같은데 일단은 이 부분은 기존의 존재하던 Context 이 있으니까 그 위에 로직을 얹어서 같이 import해오는 쪽으로 구현 방향을 잡았던 것 같습니다. 저도 개선 해봐야 할 점이라고 생각이 드네요!

그리고 렌더링 부분은 context api에서 상태가 바뀔 때 마다 구독하는 컴포넌트가 모두 리렌더링 되는 현상 때문에 혹시 불필요하게 렌더링 되는 곳이 있으시면 말씀해주시면 감사할 것 같아서 PR에 작성했습니다. 저도 일단 구현에 집중해서 불필요한 렌더링 이슈까지는 신경쓰지 못했습니다 😅

2023-05-08 22:04 UTC, greyHairChooseLife requested changes

2023-05-08 22:04 UTC, greyHairChooseLife commented on src/contexts/HabitContext.tsx
> +import { Habit } from 'interface/main';
리액트 전체를 import하는 것이 성능상 약점이 되지는 않을까요?

그리고 import에 무엇을 사용하려는지 구체적으로 적어주는 것, 아래 구현부에서 React 객체를 생략 해 주는 것 모두 나쁠게 없을 것 같은데, 전반적으로 요렇게 하신것에 어떤 이유가 있나요?

2023-05-08 22:04 UTC, greyHairChooseLife commented on src/contexts/HabitContext.tsx
> +export const HabitDispatchContext = React.createContext<React.Dispatch<{
상태값이 아닌 것을 컨텍스트로 제공하는 경우는 없을 것 같은데, 그런 경우라도 State를 명시 해 주는 것이 필요할까요?

Dispatch같은 키워드도 이 컨텍스트를 사용하는 입장에서 useReducer를 썼는지 useState를 썼는지에 관심이 있을까 싶어요. 어차피 typescript라서 어떤 setter함수들이 들어있는지 보여줄텐데요.

2023-05-08 22:04 UTC, greyHairChooseLife commented on src/contexts/HabitContextProvider.tsx
> +      return newState;
splice 메소드는 지양하는 것이 좋을 것 같아요.

물론 여기서는 불변성 관련 처리를 잘 해 주셨지만, 객체나 배열을 수정하는 메소드 보다는 변경하여 생성하는 메소드를 쓰는 편이 좀더 안전할 수 있을 것 같습니다. 물론 어디까지나 옵션이지만요.

별개로 splice는 성능 또한 좋지 않습니다. 코테 할때 저도 맨날 splice를 썼는데, 이때문에 성능 점수가 낮게 나오는 경우가 많더라고요.

저같은 경우 map을 주로 쓰는데, 추천할 만 하냐면 또 모르겠네요 ㅎㅎ 이부분도 깊은 복사니 얕은 복사니 공부할 내용이 조금 있는 듯 한데, 제가 간단히 살펴보고 전달 드릴만한 내용이 아니니 한번 공부 주제로 삼아보셔도 좋을 것 같고요!

2023-05-08 22:04 UTC, greyHairChooseLife commented on src/contexts/HabitContextProvider.tsx
> +      return [...state.filter((_, idx) => idx !== targetIdx)];
```
return state.filter(habit => habit.id !== action.payload.id)
또는
return state.filter({id} => id !== action.payload.id)
```

이렇게 하면 targetIdx 구하는 함수를 'UPDATE' case에서만 사용하도록 할 수 있을 것 같습니다. 그리고 filter 메소드는 어차피 새로운 배열을 리턴해서 spread하지 않아도 되겠습니다!

2023-05-08 22:04 UTC, greyHairChooseLife commented on src/contexts/HabitContextProvider.tsx
> +) => {
reducer 함수 파일을 분리 해 주면 더 좋을 것 같아요.

물론 여기서 context provider와 reducer가 밀접한 관계를 가지고 있지만, 둘은 엄연히 다른 일을 하기 때문입니다.

일례로, 버그가 나서 디버깅이라도 하려면 보고 된 파일 이름만으로는 어디가 문제인지 단번에 알아차리기 어렵습니다.

2023-05-08 22:04 UTC, greyHairChooseLife commented on src/index.tsx
> +import ModalPortal from 'components/Modal/ModalPortal';
context provider들을 default export로 변경 해 주신 이유는 무엇인가요?

2023-05-08 22:04 UTC, greyHairChooseLife commented on src/components/HabitList/useHabitList.tsx
> +  return { weekData, habits, getTypeOfButton, getAchieveRate, toggleComplete };
커스텀 훅을 쓰는 이유에 정답이 있는 것은 아니라고 알고있어요. 그리고 commit message에 적어주신 것 처럼 habitList 컴포넌트가 return하는 DOM요소를 구성하는 값들을 얻는 로직을 분리하는 것도 의미가 있다고 생각합니다.

하지만 custom hook이 너무 많은 일을 하고있는 것 같습니다.

너무 많은 책임을 가지고 있을 때의 문제점은 대표적으로 하나라도 문제가 생기거나, 앞으로 변경 하게 될 경우에 상관없는 다른 코드까지 살펴야 한다는 점이 있습니다.

더군다나 habits는 이유 없이 wrapping 되기도 했고, 다른 함수들도 커스텀 훅으로 만들기보단 그냥 utility함수로 만들어 쓰면 될 것 같아요. dispatch를 쓰고 있는 toggleComplete은 제외하구요.

2023-05-08 22:04 UTC, greyHairChooseLife commented on src/components/Modal/useModal.tsx
> +  };
이 커스텀 훅도 useHabitList 커스텀 훅과 마찬가지인 것 같아요. 

WEEK_DAYS나 name같은 것만 해도 그냥 modal 컴포넌트에서 import하거나 props에서 바로 갖다 써도 되는 것을 로직과 return하는 돔 요소를 분리한다는 생각으로 전부 이 훅에 넣으신 것 같아요.

input 요소들을 관리하는 커스텀 훅 정도를 분리하면 어땠을까 싶습니다.

유지보수도 그렇겠지만 이게 여러가지가 한데 있다보니까 코드를 읽고 기능을 파악하는것도 쉽지 않은 것 같아요. 구현 자체는 여러가지를 의존적이지 않게 잘 분리하셨기 때문에 단일 책임을 가진 훅이나 기타 함수들로 분리하기 어렵지 않을 것 같습니다!

2023-05-08 22:04 UTC, greyHairChooseLife commented on public/index.html
> +    <div id="modal-root"></div>
저도  modal 이용을 고려 해 봤었는데요, 저는 잘 인해가 안되더라고요. 

장점이 컴포넌트 가장 안쪽에 있으면서도(렌더링 효율) 외부 돔 요소들을 덮어 씌우는 블러처리가 가능하다인가? 하여튼 정확하게 이해하지 못했었습니다. 

창환님은 왜 모달로 하셨나요?

2023-05-08 22:04 UTC, greyHairChooseLife commented on src/lib/helpers/dateHelpers.ts
> +};
#commit 0e884e54df4393181c20e3ee63d10a85bcc46dac 에서 

> dateUtils 함수에는 가장 기본적인 것(계산하기, 비교하기, 포맷팅)을 두고 이것들을 조합해서 helpers함수에서 선언적으로 작성하고 이것을 컴포넌트나 hooks에서 이용하는 방식으로 구현했습니다.

라고 해주셨는데요, 이 설명을 보고서 '그러면 dateUtils는 helpers에 종속적인가?'라고 생각이 들었습니다.

하지만 디렉토리 위치라던가 내부에 만들어져있는 함수를 보면 무엇이 기본적인 것이고 무엇이 그것들을 조합한 것인지 저는 구분이 좀 어렵더라구요.  다시말해서 제가 뭔가 관련된 함수를 찾거나 새로 추가해야 할 때, 이것이 utils에 들어가야할지 helpers에 들어가야할지 모르겠습니다.

> (utils는 다양성을 위해 how에 집중, helpers는 선언적으로 작성하기 위해 what에 집중)

PR 메시지에서는 위 처럼 말씀 해 주셨는데 이것도 이해가 잘 안됩니다!! ㅠㅠㅠㅠ  

저는 선언적으로 코딩 한다는게 적절한 함수 이름과 표현력 좋은 타입을 쓴다는걸로 이해하고 있거든요?  구현부를 딱히 보지 않아도 함수를 어떻게 사용하고 결과는 어떨지 쉽게 예상이 된다는게 선언적이라는거고, 구현부는 필요 할 때나 살펴 보도록이요.

이렇게 분리 되어서 얻는 이점이 뭐라고 생각하시는지 좀 더 자세히 설명 부탁드려요.

---

또, helpers / someComponent.helpers 로도 구분되어있는데, 이것은 어떤 구분인가요?

> 그에 따라 PeriodContext가 이용하는 함수들은 helpers라고 판단하여 새로운 파일을 생성하고 helpers함수만 모아놨습니다

이 설명을 봐도 잘 모르겠습니다.

2023-05-08 22:04 UTC, greyHairChooseLife commented on src/components/HabitList/useHabitList.tsx
> +  };
이것도 위에서 이미 리뷰한 것의 연장선이긴 한데요, 이렇게 파라미터에 전달 받은 값을 가지고 단순 계산한 값을 얻는 것은 util이든 helper든 두고서 import해서 사용하는게 좋을 것 같아요.

만약 그랬다면 habitList 컴포넌트에서도, ProgressBar 컴포넌트에서도 간단히 import해서 사용하고, progressBar.helper.ts 같은 파일은 필요하지 않았을 것 같습니다. 이 파일 안에 코드 자체도 중복이고요.

2023-05-08 22:10 UTC, greyHairChooseLife requested changes
고생하셨습니다, 창환님 :+1: 

제가 커밋 자체에도 메시지를 남겼는데, 그것들은 여기 리뷰 타임라인에는 기록되지 않더라고요. [commit tab](https://github.com/wanted-pre-onboarding-side-project/habit-tracker/pull/50/commits) 에서는 확인하실 수 있어요!

---

커밋 메시지에 제목이랑 내용이 커밋메시지 템플릿에서 잡아주는 레이아웃에 맞지 않는 경우가 많더라고요. 제목은 80자, 내용은 120자였나 그럴거에요.  템플릿 찰 보시면 글자수도 맞추기 쉽도록 가이드라인이 있고 또 내용 부분은 쓰다 보면 알아서 줄바꿈이 되기도 합니다.

이 외에 렌더링 효율성 같은 부분은 뭔가 신경 쓴 부분이 있어서 알려주신다면 몰라도 먼저 짚어보는 것은 쉽지 않은 것 같아요. 다만 context를 providing 할 때, value에 객체 자체를 넣어주시면callback등으로 감싸나 마나 소용이 없습니다.

`<Context.provider value = {객체}>` 이렇게 되면 value는 매번 항상 바뀌기 때문에 맨날 리렌더링 되거든요. 

그래서 객체를 providing 해 주실 때 useMemo로 memoization 해주시면 렌더링 효율성 측면에서는 더 나아질 것 같습니다!

--- 

데이터 타입에 관해서도 이야기 해 보고 싶은 부분이 좀 있습니다.

데이터 타입의 경우 저는 수행 기록인 record를 따로 저장했거든요. 매 주마다 record를 끊어서 localStorage에 저장했습니다. 

왜냐면 배열이란게 많은 양의 데이터를 보관하기에 좋은 데이터 타입은 아니거든요. 특히 그 안에서 특정 값에 접근해야 할 때에 효율성이 많이 떨어지는 것으로 압니다. 저희가 딱 그렇죠. period에 따라서 특정 인덱스에 접근하고, 때로는 삭제도 하고요.

또 하나의 문제는 localStorage의 각 key 값에 저장 할 수 있는 용량에 제한이 있다는 것입니다. 총 저장량은 보통 5mb이지만요.

---

제가 창환님 pr로 체크아웃 해서 로컬호스트로 띄우고 많이 만져봤거든요. 몇 가지 사용상 버그가 있더라고요. 그땐 정리 해 두지 않았는데, 발견하는 대로 여기 아래에 업데이트 하겠습니다.

2023-05-14 04:15 UTC, chadseok commented on src/contexts/HabitContext.tsx
> +import { Habit } from 'interface/main';
저는 컴포넌트에서 React의 API들을 사용했다가 나중에 사용하지 않게 되서 빼버린 경우를 많이 겪다보니 (예를 들면 useEffect를 사용했다가 필요없어 빼버린 경우) 본문의 코드 뿐만 아니라 상단에 import해오는 곳도 바꾸어야 해서 귀찮았던 적이 있었습니다. 그럴 때 전체를 import해서 사용하는 것이 편하여서 전체를 import하는 방식으로 사용하고 있습니다

성능 문제는 제가 알기로는 번들링 할 때 tree-shaking을 해서 사용하지 않는 것들은 걸러주는 것으로 알고 있습니다

2023-05-14 04:19 UTC, chadseok commented on src/contexts/HabitContext.tsx
> +export const HabitDispatchContext = React.createContext<React.Dispatch<{
이 네이밍은 처음에 지을 때 useReducer의 반환값인 state와 dispatch를 나누어 분리할 때 결정되었습니다.

```js
const [state, dispatch] = React.useReducer()
```

2023-05-14 04:20 UTC, chadseok commented on src/contexts/HabitContextProvider.tsx
> +      return newState;
넵! 참고해보겠습니다

2023-05-14 04:23 UTC, chadseok commented on src/contexts/HabitContextProvider.tsx
> +      return [...state.filter((_, idx) => idx !== targetIdx)];
이게 case문 안에서 변수 선언이 lint룰에 막혀서 제가 밖에서 선언했는데 선언하고 나니 update만 사용하는 것 같아 다른 부분도 적용시켰습니다. 

아 그리고 spread 부분은 피드백 감사합니다!

2023-05-14 04:24 UTC, chadseok commented on src/index.tsx
> +import ModalPortal from 'components/Modal/ModalPortal';
하나만 내보내기 때문입니다

2023-05-14 04:26 UTC, chadseok commented on src/components/HabitList/useHabitList.tsx
> +  return { weekData, habits, getTypeOfButton, getAchieveRate, toggleComplete };
네 확실히 많은 일을 하고 있는 것 같습니다. 그래서 @jiyeon2 님 께서 훅을 여러개로 분리해보는 것을 얘기해보셨는데 한번 적용해보도록 하겠습니다

2023-05-14 04:27 UTC, chadseok commented on src/components/Modal/useModal.tsx
> +  };
넵 알겠습니다

2023-05-14 04:38 UTC, chadseok commented on src/lib/helpers/dateHelpers.ts
> +};
utils의 이름을 보면 `getFormattedString`, `getCalcuatedDate` 이렇게 되어있는데 이걸 바로 컴포넌트나 다른 훅에서 사용할 수 있지만 formattedString이나 calcuatedDate를 구하는 것이 함수에서 어떤 역할을 하는 가가 명확하기 않습니다. 그래서 저는 helpers라는 파일을 이용해서 새로운 함수를 만들고 이름으로 의미를 확실하게 부여하도록 작성했습니다. (`isSameWeek`, `isAfterDay`)

utils함수들은 날짜를 조작하고 값을 가져오는데 집중하고 있어서 어떻게 바꿀것인가 (how)에 대한 로직 helpers함수들은 어떻게 될것인가 (what)에 대한 로직을 담고있습니다. 잘 살펴보시면 수많은 helpers함수들은 다양한 utils함수들을 조합해서 작성되어있습니다.

밖의 최상단 helpers폴더는 공용적으로 사용하는 helpers파일들을 모아둔 것이고 안의 someComponent.helpers는 이 컴포넌트에서만 사용하는 helpers를 모아 둔 것 입니다

2023-05-14 04:41 UTC, chadseok commented on src/components/HabitList/useHabitList.tsx
> +  };
옮겨도 되지만 저는 아무래도 hooks와 좀 더 연관이 있기도 하고 같이 내보내고 싶어서 묶어두었습니다

그리고 ProgressBar에서 사용하는 로직과는 좀 달라서 따로 import해서 사용할 수는 없습니다

2023-05-14 04:42 UTC, chadseok commented on src/contexts/HabitContextProvider.tsx
> +) => {
넵! 한번 고려해보겠습니다

2023-06-01 14:52 UTC, greyHairChooseLife approved these changes

2023-06-01 15:00 UTC, merged