Feature #49
wanted-pre-onboarding-side-project/habit-tracker pull request #51
Opened 2023-04-27 02:24 UTC by jiyeon2

### 1. 무슨 이유로 코드를 추가/변경 했는지

목적 : #49 에서 정의된 기능 구현

작업한 내용
- drawer 형태의 모달 컴포넌트 작성
- 해빗 생성 기능 추가
- 요일 표시, 요일별 습관 체크박스 표시
- 습관 체크(record 생성) 기능 추가
- 해뱃 삭제 다이얼로그 추가
- 주간 달성률 계산 로직 수정(record 데이터 반영)

### 2. 파일 구조와 용도
- components/habits : 해빗리스트 관련 컴포넌트 
- components/overlay: 모달, 다이얼로그 관련 컴포넌트 (모달에 들어가는 생성, 수정폼도 여기 포함되어 있음)

### 3. 어떤 부분에 리뷰어가 집중하면 좋을지
기능 구현에 급급해 불필요하게 긴 코드나 비효율적인 코드가 있을 수 있습니다. 조금이라도 이상한 부분은 짧게라도 코멘트 남겨주시면 감사하겠습니다.

모달 컴포넌트는 chakra-ui의 modal과 같은 형태로 사용하고 싶어 모달 컨텍스트를 삭제하였습니다

습관 체크 데이터는 RecordContextProvider에 state로 존재합니다
```
export interface HabitRecord {
  habitId: number; // habit id 저장하여 어떤 습관의 체크 데이터인지 구분하기 위함
  records: string[]; // [2023-04-20, 2023-04-21] 처럼 string 형태로 체크한 날짜를 저장
}
```

작업하지 못한 부분 : 로컬 스토리지 적용하여 데이터 저장, 생성 수정 폼 유효성 검사, 모달 애니메이션 적용 미흡

### 4. 관련 스크린샷 or GIF
![image](https://user-images.githubusercontent.com/18395475/234742238-078009c8-b27c-4aa2-8809-027de245984a.png)

2023-04-27 08:35 UTC, chadseok commented on src/components/controller/parts/AddHabitBtn.tsx
> +  };
혹시 setTimeout을 준 로직은 어떤 기능과 관련 있는지 여쭤봐도 될까요?

2023-04-27 08:41 UTC, chadseok commented on src/contexts/RecordContextProvider.tsx
> +    }) => {
record들이 선택할 수 있는 칸 하나 하나마다 생성 되는 건가요? 저는 habit안에 다 모아두는 방식으로 접근해서 @jiyeon2 님은 어떻게 구현하셨는지 궁금하네요

2023-04-27 08:53 UTC, chadseok commented on src/components/habits/parts/HabitContextMenu.tsx
> +}) => {
혹시 HabitContextMenu가 어떤 기능인지 알 수 있을까요? HabitList 기능안에 modal 관련 기능이 있는 것 같은데 어떤 흐름으로 흘러가는지 알고 싶습니다!

2023-04-27 09:06 UTC, chadseok requested changes
구현해주시느라 고생하셨습니다! 혹시 제 PR 테스트는 clone을 하신 걸까요? 저도 지연님꺼 테스트 해보면서 코드에 대해 파악해보고 싶은데 어떻게 하셨는지 궁금합니다

2023-04-27 12:19 UTC, jiyeon2 commented
> 구현해주시느라 고생하셨습니다! 혹시 제 PR 테스트는 clone을 하신 걸까요? 저도 지연님꺼 테스트 해보면서 코드에 대해 파악해보고 싶은데 어떻게 하셨는지 궁금합니다

네 저는 @chadseok 님이 포크하신 저장소를 clone 해서 
작업하신 branch를 fetch 해서 실행하였습니다!

2023-04-27 12:25 UTC, jiyeon2 commented on src/components/habits/parts/HabitContextMenu.tsx
> +}) => {
@chadseok 님이 작업하신 Popover와 같은 역할을 하는 컴포넌트입니다(특정 해빗 수정, 삭제 버튼)

해빗 리스트에서 해빗 이름을 클릭하면 HabitContextMenu 컴포넌트가 이름 옆에 표시됩니다

이름에 context가 들어가서 react 의 컨텍스트와 관련 있다고 보일 수도 있겠네요..
마우스 우클릭 했을 때 표시되는 컨텍스트 메뉴와 비슷하다고 생각해서 이름을 저렇게 지었습니다!

2023-04-27 12:33 UTC, jiyeon2 commented on src/contexts/RecordContextProvider.tsx
> +    }) => {
```
const records = [
 {habitId: 1, records: ['2023-04-20', '2023-04-21']},
 {habitId: 2, records: ['2023-04-20']}
]
```
habit은 기존 데이터 형태 그대로 가지고 있고
records 의 구조는 위와 같습니다

칸마다 생성하지 않고
체크한 날짜만 yyyy-mm-dd문자열 형태로 저장합니다
체크를 해제하면(handleChangeRecord에 넘기는 type이 unmark이면) records배열 내에서 날짜 문자열을 삭제합니다

창환님은 `habit.recordedDates = {'2021-04-20': 'active', '2021-04-21': 'active'}` 형태로 만드셨더라고요
저는 inactive인 경우를 저장하지 않고 active인 경우만 저장하는 형태입니다!

2023-04-27 12:42 UTC, jiyeon2 commented on src/components/controller/parts/AddHabitBtn.tsx
> +  };
모달이 열릴 때, 닫힐 때 슬라이드 되는 애니메이션을 넣고 싶어서 
.open이라는 클래스를 떼었다 붙였다 하는 형태를 만들었는데

isOpen이 false인 경우 Modal 컴포넌트가 바로 언마운트되어서
.open 클래스를 떼었을 때 나타나는 transition 효과를 볼 수가 없더라고요..

임시방편으로 
스르륵 사라지는 transition 효과가 끝나는 500ms 이후 unmount 되도록 하기 위해 setTimeout을 사용하였습니다
500ms 는 .modalContainer 클래스에 적용된 transition 지속시간과 동일합니다

2023-04-28 01:42 UTC, chadseok commented on src/contexts/RecordContextProvider.tsx
> +    }) => {
habit 하나당 record도 하나씩 있다면 같이 두는 것도 고려해볼 것 같은데 따로 두었을 때 좋은 점이 있을 까요?

2023-04-28 01:50 UTC, chadseok commented on src/components/habits/parts/HabitContextMenu.tsx
> +}) => {
아 그렇군요! 처음 봤을 때는 파일 이름으로 Context API와 관련이 있는 줄 알았습니다. 제가 컨텍스트 메뉴라는 이름이 생소해서 바로 못 알아봤네요. 😅

2023-06-10 05:36 UTC, closed without merging